#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_SharePoint
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Baza_technol")]
	public partial class BAZA_RYSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKartoteka_rysunków_konstrukcyjnych(Kartoteka_rysunków_konstrukcyjnych instance);
    partial void UpdateKartoteka_rysunków_konstrukcyjnych(Kartoteka_rysunków_konstrukcyjnych instance);
    partial void DeleteKartoteka_rysunków_konstrukcyjnych(Kartoteka_rysunków_konstrukcyjnych instance);
    partial void InsertKarta_zmian_norm_pracy_kopia_zła(Karta_zmian_norm_pracy_kopia_zła instance);
    partial void UpdateKarta_zmian_norm_pracy_kopia_zła(Karta_zmian_norm_pracy_kopia_zła instance);
    partial void DeleteKarta_zmian_norm_pracy_kopia_zła(Karta_zmian_norm_pracy_kopia_zła instance);
    #endregion
		
		public BAZA_RYSDataContext() : 
				base(global::WebService_SharePoint.Properties.Settings.Default.Baza_technolConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public BAZA_RYSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BAZA_RYSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BAZA_RYSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BAZA_RYSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kartoteka_rysunków_konstrukcyjnych> Kartoteka_rysunków_konstrukcyjnyches
		{
			get
			{
				return this.GetTable<Kartoteka_rysunków_konstrukcyjnych>();
			}
		}
		
		public System.Data.Linq.Table<Karta_zmian_norm_pracy_kopia_zła> Karta_zmian_norm_pracy_kopia_złas
		{
			get
			{
				return this.GetTable<Karta_zmian_norm_pracy_kopia_zła>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Kartoteka rysunków konstrukcyjnych]")]
	public partial class Kartoteka_rysunków_konstrukcyjnych : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NrRysunku;
		
		private string _NazwaRysunku;
		
		private string _NazwaRysunkuAng;
		
		private string _Opis;
		
		private string _Rysunek;
		
		private string _RysunekKatalog;
		
		private System.Nullable<double> _PowZewn_dm2;
		
		private System.Nullable<System.DateTime> _DataWprowadzenia;
		
		private System.Nullable<int> _NrUruchomienia;
		
		private string _Schemat;
		
		private string _Nazwa_GB;
		
		private string _Nazwa_D;
		
		private string _Nazwa_F;
		
		private string _Nazwa_ES;
		
		private string _Nazwa_IT;
		
		private string _Nazwa_CZ;
		
		private string _Nazwa_SK;
		
		private string _Nazwa_RUS;
		
		private string _Nazwa_PL;
		
		private string _Pikt1;
		
		private string _Pikt1_Opis;
		
		private string _Pikt2;
		
		private string _Pikt2_Opis;
		
		private string _Pikt3;
		
		private string _Pikt3_Opis;
		
		private string _Pikt4;
		
		private string _Pikt4_Opis;
		
		private string _Pikt5;
		
		private string _Pikt5_Opis;
		
		private string _Pikt6;
		
		private string _Pikt6_Opis;
		
		private string _Pikt7;
		
		private string _Pikt7_Opis;
		
		private string _Pikt8;
		
		private string _Pikt8_Opis;
		
		private string _Pikt9;
		
		private string _Pikt9_Opis;
		
		private string _Pikt10;
		
		private string _Pikt10_Opis;
		
		private string _Pikt11;
		
		private string _Pikt11_Opis;
		
		private string _Pikt12;
		
		private string _Pikt12_Opis;
		
		private System.Nullable<int> _CennikLiczbaKolumn;
		
		private string _Nazwa_GB_Rough;
		
		private string _Nazwa_D_Rough;
		
		private string _Nazwa_F_Rough;
		
		private string _Nazwa_ES_Rough;
		
		private string _Nazwa_IT_Rough;
		
		private string _Nazwa_CZ_Rough;
		
		private string _Nazwa_SK_Rough;
		
		private string _Nazwa_RUS_Rough;
		
		private string _Nazwa_PL_Rough;
		
		private string _Nazwa_GB_1;
		
		private string _Nazwa_D_1;
		
		private string _Nazwa_F_1;
		
		private string _Nazwa_ES_1;
		
		private string _Nazwa_IT_1;
		
		private string _Nazwa_CZ_1;
		
		private string _Nazwa_SK_1;
		
		private string _Nazwa_RUS_1;
		
		private string _Nazwa_PL_1;
		
		private string _Nazwa_GB_2;
		
		private string _Nazwa_D_2;
		
		private string _Nazwa_F_2;
		
		private string _Nazwa_ES_2;
		
		private string _Nazwa_IT_2;
		
		private string _Nazwa_CZ_2;
		
		private string _Nazwa_SK_2;
		
		private string _Nazwa_RUS_2;
		
		private string _Nazwa_PL_2;
		
		private string _Nazwa_GB_3;
		
		private string _Nazwa_D_3;
		
		private string _Nazwa_F_3;
		
		private string _Nazwa_ES_3;
		
		private string _Nazwa_IT_3;
		
		private string _Nazwa_CZ_3;
		
		private string _Nazwa_SK_3;
		
		private string _Nazwa_RUS_3;
		
		private string _Nazwa_PL_3;
		
		private string _Zweryfikowano_Ikonki;
		
		private string _RysunekSzlif;
		
		private System.Nullable<bool> _Archiwum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNrRysunkuChanging(string value);
    partial void OnNrRysunkuChanged();
    partial void OnNazwaRysunkuChanging(string value);
    partial void OnNazwaRysunkuChanged();
    partial void OnNazwaRysunkuAngChanging(string value);
    partial void OnNazwaRysunkuAngChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    partial void OnRysunekChanging(string value);
    partial void OnRysunekChanged();
    partial void OnRysunekKatalogChanging(string value);
    partial void OnRysunekKatalogChanged();
    partial void OnPowZewn_dm2Changing(System.Nullable<double> value);
    partial void OnPowZewn_dm2Changed();
    partial void OnDataWprowadzeniaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataWprowadzeniaChanged();
    partial void OnNrUruchomieniaChanging(System.Nullable<int> value);
    partial void OnNrUruchomieniaChanged();
    partial void OnSchematChanging(string value);
    partial void OnSchematChanged();
    partial void OnNazwa_GBChanging(string value);
    partial void OnNazwa_GBChanged();
    partial void OnNazwa_DChanging(string value);
    partial void OnNazwa_DChanged();
    partial void OnNazwa_FChanging(string value);
    partial void OnNazwa_FChanged();
    partial void OnNazwa_ESChanging(string value);
    partial void OnNazwa_ESChanged();
    partial void OnNazwa_ITChanging(string value);
    partial void OnNazwa_ITChanged();
    partial void OnNazwa_CZChanging(string value);
    partial void OnNazwa_CZChanged();
    partial void OnNazwa_SKChanging(string value);
    partial void OnNazwa_SKChanged();
    partial void OnNazwa_RUSChanging(string value);
    partial void OnNazwa_RUSChanged();
    partial void OnNazwa_PLChanging(string value);
    partial void OnNazwa_PLChanged();
    partial void OnPikt1Changing(string value);
    partial void OnPikt1Changed();
    partial void OnPikt1_OpisChanging(string value);
    partial void OnPikt1_OpisChanged();
    partial void OnPikt2Changing(string value);
    partial void OnPikt2Changed();
    partial void OnPikt2_OpisChanging(string value);
    partial void OnPikt2_OpisChanged();
    partial void OnPikt3Changing(string value);
    partial void OnPikt3Changed();
    partial void OnPikt3_OpisChanging(string value);
    partial void OnPikt3_OpisChanged();
    partial void OnPikt4Changing(string value);
    partial void OnPikt4Changed();
    partial void OnPikt4_OpisChanging(string value);
    partial void OnPikt4_OpisChanged();
    partial void OnPikt5Changing(string value);
    partial void OnPikt5Changed();
    partial void OnPikt5_OpisChanging(string value);
    partial void OnPikt5_OpisChanged();
    partial void OnPikt6Changing(string value);
    partial void OnPikt6Changed();
    partial void OnPikt6_OpisChanging(string value);
    partial void OnPikt6_OpisChanged();
    partial void OnPikt7Changing(string value);
    partial void OnPikt7Changed();
    partial void OnPikt7_OpisChanging(string value);
    partial void OnPikt7_OpisChanged();
    partial void OnPikt8Changing(string value);
    partial void OnPikt8Changed();
    partial void OnPikt8_OpisChanging(string value);
    partial void OnPikt8_OpisChanged();
    partial void OnPikt9Changing(string value);
    partial void OnPikt9Changed();
    partial void OnPikt9_OpisChanging(string value);
    partial void OnPikt9_OpisChanged();
    partial void OnPikt10Changing(string value);
    partial void OnPikt10Changed();
    partial void OnPikt10_OpisChanging(string value);
    partial void OnPikt10_OpisChanged();
    partial void OnPikt11Changing(string value);
    partial void OnPikt11Changed();
    partial void OnPikt11_OpisChanging(string value);
    partial void OnPikt11_OpisChanged();
    partial void OnPikt12Changing(string value);
    partial void OnPikt12Changed();
    partial void OnPikt12_OpisChanging(string value);
    partial void OnPikt12_OpisChanged();
    partial void OnCennikLiczbaKolumnChanging(System.Nullable<int> value);
    partial void OnCennikLiczbaKolumnChanged();
    partial void OnNazwa_GB_RoughChanging(string value);
    partial void OnNazwa_GB_RoughChanged();
    partial void OnNazwa_D_RoughChanging(string value);
    partial void OnNazwa_D_RoughChanged();
    partial void OnNazwa_F_RoughChanging(string value);
    partial void OnNazwa_F_RoughChanged();
    partial void OnNazwa_ES_RoughChanging(string value);
    partial void OnNazwa_ES_RoughChanged();
    partial void OnNazwa_IT_RoughChanging(string value);
    partial void OnNazwa_IT_RoughChanged();
    partial void OnNazwa_CZ_RoughChanging(string value);
    partial void OnNazwa_CZ_RoughChanged();
    partial void OnNazwa_SK_RoughChanging(string value);
    partial void OnNazwa_SK_RoughChanged();
    partial void OnNazwa_RUS_RoughChanging(string value);
    partial void OnNazwa_RUS_RoughChanged();
    partial void OnNazwa_PL_RoughChanging(string value);
    partial void OnNazwa_PL_RoughChanged();
    partial void OnNazwa_GB_1Changing(string value);
    partial void OnNazwa_GB_1Changed();
    partial void OnNazwa_D_1Changing(string value);
    partial void OnNazwa_D_1Changed();
    partial void OnNazwa_F_1Changing(string value);
    partial void OnNazwa_F_1Changed();
    partial void OnNazwa_ES_1Changing(string value);
    partial void OnNazwa_ES_1Changed();
    partial void OnNazwa_IT_1Changing(string value);
    partial void OnNazwa_IT_1Changed();
    partial void OnNazwa_CZ_1Changing(string value);
    partial void OnNazwa_CZ_1Changed();
    partial void OnNazwa_SK_1Changing(string value);
    partial void OnNazwa_SK_1Changed();
    partial void OnNazwa_RUS_1Changing(string value);
    partial void OnNazwa_RUS_1Changed();
    partial void OnNazwa_PL_1Changing(string value);
    partial void OnNazwa_PL_1Changed();
    partial void OnNazwa_GB_2Changing(string value);
    partial void OnNazwa_GB_2Changed();
    partial void OnNazwa_D_2Changing(string value);
    partial void OnNazwa_D_2Changed();
    partial void OnNazwa_F_2Changing(string value);
    partial void OnNazwa_F_2Changed();
    partial void OnNazwa_ES_2Changing(string value);
    partial void OnNazwa_ES_2Changed();
    partial void OnNazwa_IT_2Changing(string value);
    partial void OnNazwa_IT_2Changed();
    partial void OnNazwa_CZ_2Changing(string value);
    partial void OnNazwa_CZ_2Changed();
    partial void OnNazwa_SK_2Changing(string value);
    partial void OnNazwa_SK_2Changed();
    partial void OnNazwa_RUS_2Changing(string value);
    partial void OnNazwa_RUS_2Changed();
    partial void OnNazwa_PL_2Changing(string value);
    partial void OnNazwa_PL_2Changed();
    partial void OnNazwa_GB_3Changing(string value);
    partial void OnNazwa_GB_3Changed();
    partial void OnNazwa_D_3Changing(string value);
    partial void OnNazwa_D_3Changed();
    partial void OnNazwa_F_3Changing(string value);
    partial void OnNazwa_F_3Changed();
    partial void OnNazwa_ES_3Changing(string value);
    partial void OnNazwa_ES_3Changed();
    partial void OnNazwa_IT_3Changing(string value);
    partial void OnNazwa_IT_3Changed();
    partial void OnNazwa_CZ_3Changing(string value);
    partial void OnNazwa_CZ_3Changed();
    partial void OnNazwa_SK_3Changing(string value);
    partial void OnNazwa_SK_3Changed();
    partial void OnNazwa_RUS_3Changing(string value);
    partial void OnNazwa_RUS_3Changed();
    partial void OnNazwa_PL_3Changing(string value);
    partial void OnNazwa_PL_3Changed();
    partial void OnZweryfikowano_IkonkiChanging(string value);
    partial void OnZweryfikowano_IkonkiChanged();
    partial void OnRysunekSzlifChanging(string value);
    partial void OnRysunekSzlifChanged();
    partial void OnArchiwumChanging(System.Nullable<bool> value);
    partial void OnArchiwumChanged();
    #endregion
		
		public Kartoteka_rysunków_konstrukcyjnych()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrRysunku", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NrRysunku
		{
			get
			{
				return this._NrRysunku;
			}
			set
			{
				if ((this._NrRysunku != value))
				{
					this.OnNrRysunkuChanging(value);
					this.SendPropertyChanging();
					this._NrRysunku = value;
					this.SendPropertyChanged("NrRysunku");
					this.OnNrRysunkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazwaRysunku", DbType="NVarChar(66)")]
		public string NazwaRysunku
		{
			get
			{
				return this._NazwaRysunku;
			}
			set
			{
				if ((this._NazwaRysunku != value))
				{
					this.OnNazwaRysunkuChanging(value);
					this.SendPropertyChanging();
					this._NazwaRysunku = value;
					this.SendPropertyChanged("NazwaRysunku");
					this.OnNazwaRysunkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazwaRysunkuAng", DbType="NVarChar(66)")]
		public string NazwaRysunkuAng
		{
			get
			{
				return this._NazwaRysunkuAng;
			}
			set
			{
				if ((this._NazwaRysunkuAng != value))
				{
					this.OnNazwaRysunkuAngChanging(value);
					this.SendPropertyChanging();
					this._NazwaRysunkuAng = value;
					this.SendPropertyChanged("NazwaRysunkuAng");
					this.OnNazwaRysunkuAngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(100)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rysunek", DbType="NVarChar(50)")]
		public string Rysunek
		{
			get
			{
				return this._Rysunek;
			}
			set
			{
				if ((this._Rysunek != value))
				{
					this.OnRysunekChanging(value);
					this.SendPropertyChanging();
					this._Rysunek = value;
					this.SendPropertyChanged("Rysunek");
					this.OnRysunekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RysunekKatalog", DbType="NVarChar(50)")]
		public string RysunekKatalog
		{
			get
			{
				return this._RysunekKatalog;
			}
			set
			{
				if ((this._RysunekKatalog != value))
				{
					this.OnRysunekKatalogChanging(value);
					this.SendPropertyChanging();
					this._RysunekKatalog = value;
					this.SendPropertyChanged("RysunekKatalog");
					this.OnRysunekKatalogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PowZewn_dm2", DbType="Float")]
		public System.Nullable<double> PowZewn_dm2
		{
			get
			{
				return this._PowZewn_dm2;
			}
			set
			{
				if ((this._PowZewn_dm2 != value))
				{
					this.OnPowZewn_dm2Changing(value);
					this.SendPropertyChanging();
					this._PowZewn_dm2 = value;
					this.SendPropertyChanged("PowZewn_dm2");
					this.OnPowZewn_dm2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataWprowadzenia", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataWprowadzenia
		{
			get
			{
				return this._DataWprowadzenia;
			}
			set
			{
				if ((this._DataWprowadzenia != value))
				{
					this.OnDataWprowadzeniaChanging(value);
					this.SendPropertyChanging();
					this._DataWprowadzenia = value;
					this.SendPropertyChanged("DataWprowadzenia");
					this.OnDataWprowadzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrUruchomienia", DbType="Int")]
		public System.Nullable<int> NrUruchomienia
		{
			get
			{
				return this._NrUruchomienia;
			}
			set
			{
				if ((this._NrUruchomienia != value))
				{
					this.OnNrUruchomieniaChanging(value);
					this.SendPropertyChanging();
					this._NrUruchomienia = value;
					this.SendPropertyChanged("NrUruchomienia");
					this.OnNrUruchomieniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schemat", DbType="NVarChar(50)")]
		public string Schemat
		{
			get
			{
				return this._Schemat;
			}
			set
			{
				if ((this._Schemat != value))
				{
					this.OnSchematChanging(value);
					this.SendPropertyChanging();
					this._Schemat = value;
					this.SendPropertyChanged("Schemat");
					this.OnSchematChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_GB", DbType="NVarChar(150)")]
		public string Nazwa_GB
		{
			get
			{
				return this._Nazwa_GB;
			}
			set
			{
				if ((this._Nazwa_GB != value))
				{
					this.OnNazwa_GBChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_GB = value;
					this.SendPropertyChanged("Nazwa_GB");
					this.OnNazwa_GBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_D", DbType="NVarChar(150)")]
		public string Nazwa_D
		{
			get
			{
				return this._Nazwa_D;
			}
			set
			{
				if ((this._Nazwa_D != value))
				{
					this.OnNazwa_DChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_D = value;
					this.SendPropertyChanged("Nazwa_D");
					this.OnNazwa_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_F", DbType="NVarChar(150)")]
		public string Nazwa_F
		{
			get
			{
				return this._Nazwa_F;
			}
			set
			{
				if ((this._Nazwa_F != value))
				{
					this.OnNazwa_FChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_F = value;
					this.SendPropertyChanged("Nazwa_F");
					this.OnNazwa_FChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_ES", DbType="NVarChar(150)")]
		public string Nazwa_ES
		{
			get
			{
				return this._Nazwa_ES;
			}
			set
			{
				if ((this._Nazwa_ES != value))
				{
					this.OnNazwa_ESChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_ES = value;
					this.SendPropertyChanged("Nazwa_ES");
					this.OnNazwa_ESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_IT", DbType="NVarChar(150)")]
		public string Nazwa_IT
		{
			get
			{
				return this._Nazwa_IT;
			}
			set
			{
				if ((this._Nazwa_IT != value))
				{
					this.OnNazwa_ITChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_IT = value;
					this.SendPropertyChanged("Nazwa_IT");
					this.OnNazwa_ITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_CZ", DbType="NVarChar(150)")]
		public string Nazwa_CZ
		{
			get
			{
				return this._Nazwa_CZ;
			}
			set
			{
				if ((this._Nazwa_CZ != value))
				{
					this.OnNazwa_CZChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_CZ = value;
					this.SendPropertyChanged("Nazwa_CZ");
					this.OnNazwa_CZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_SK", DbType="NVarChar(150)")]
		public string Nazwa_SK
		{
			get
			{
				return this._Nazwa_SK;
			}
			set
			{
				if ((this._Nazwa_SK != value))
				{
					this.OnNazwa_SKChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_SK = value;
					this.SendPropertyChanged("Nazwa_SK");
					this.OnNazwa_SKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_RUS", DbType="NVarChar(150)")]
		public string Nazwa_RUS
		{
			get
			{
				return this._Nazwa_RUS;
			}
			set
			{
				if ((this._Nazwa_RUS != value))
				{
					this.OnNazwa_RUSChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_RUS = value;
					this.SendPropertyChanged("Nazwa_RUS");
					this.OnNazwa_RUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_PL", DbType="NVarChar(150)")]
		public string Nazwa_PL
		{
			get
			{
				return this._Nazwa_PL;
			}
			set
			{
				if ((this._Nazwa_PL != value))
				{
					this.OnNazwa_PLChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_PL = value;
					this.SendPropertyChanged("Nazwa_PL");
					this.OnNazwa_PLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt1", DbType="NVarChar(7)")]
		public string Pikt1
		{
			get
			{
				return this._Pikt1;
			}
			set
			{
				if ((this._Pikt1 != value))
				{
					this.OnPikt1Changing(value);
					this.SendPropertyChanging();
					this._Pikt1 = value;
					this.SendPropertyChanged("Pikt1");
					this.OnPikt1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt1_Opis", DbType="NVarChar(15)")]
		public string Pikt1_Opis
		{
			get
			{
				return this._Pikt1_Opis;
			}
			set
			{
				if ((this._Pikt1_Opis != value))
				{
					this.OnPikt1_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt1_Opis = value;
					this.SendPropertyChanged("Pikt1_Opis");
					this.OnPikt1_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt2", DbType="NVarChar(7)")]
		public string Pikt2
		{
			get
			{
				return this._Pikt2;
			}
			set
			{
				if ((this._Pikt2 != value))
				{
					this.OnPikt2Changing(value);
					this.SendPropertyChanging();
					this._Pikt2 = value;
					this.SendPropertyChanged("Pikt2");
					this.OnPikt2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt2_Opis", DbType="NVarChar(10)")]
		public string Pikt2_Opis
		{
			get
			{
				return this._Pikt2_Opis;
			}
			set
			{
				if ((this._Pikt2_Opis != value))
				{
					this.OnPikt2_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt2_Opis = value;
					this.SendPropertyChanged("Pikt2_Opis");
					this.OnPikt2_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt3", DbType="NVarChar(7)")]
		public string Pikt3
		{
			get
			{
				return this._Pikt3;
			}
			set
			{
				if ((this._Pikt3 != value))
				{
					this.OnPikt3Changing(value);
					this.SendPropertyChanging();
					this._Pikt3 = value;
					this.SendPropertyChanged("Pikt3");
					this.OnPikt3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt3_Opis", DbType="NVarChar(10)")]
		public string Pikt3_Opis
		{
			get
			{
				return this._Pikt3_Opis;
			}
			set
			{
				if ((this._Pikt3_Opis != value))
				{
					this.OnPikt3_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt3_Opis = value;
					this.SendPropertyChanged("Pikt3_Opis");
					this.OnPikt3_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt4", DbType="NVarChar(7)")]
		public string Pikt4
		{
			get
			{
				return this._Pikt4;
			}
			set
			{
				if ((this._Pikt4 != value))
				{
					this.OnPikt4Changing(value);
					this.SendPropertyChanging();
					this._Pikt4 = value;
					this.SendPropertyChanged("Pikt4");
					this.OnPikt4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt4_Opis", DbType="NVarChar(10)")]
		public string Pikt4_Opis
		{
			get
			{
				return this._Pikt4_Opis;
			}
			set
			{
				if ((this._Pikt4_Opis != value))
				{
					this.OnPikt4_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt4_Opis = value;
					this.SendPropertyChanged("Pikt4_Opis");
					this.OnPikt4_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt5", DbType="NVarChar(7)")]
		public string Pikt5
		{
			get
			{
				return this._Pikt5;
			}
			set
			{
				if ((this._Pikt5 != value))
				{
					this.OnPikt5Changing(value);
					this.SendPropertyChanging();
					this._Pikt5 = value;
					this.SendPropertyChanged("Pikt5");
					this.OnPikt5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt5_Opis", DbType="NVarChar(10)")]
		public string Pikt5_Opis
		{
			get
			{
				return this._Pikt5_Opis;
			}
			set
			{
				if ((this._Pikt5_Opis != value))
				{
					this.OnPikt5_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt5_Opis = value;
					this.SendPropertyChanged("Pikt5_Opis");
					this.OnPikt5_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt6", DbType="NVarChar(7)")]
		public string Pikt6
		{
			get
			{
				return this._Pikt6;
			}
			set
			{
				if ((this._Pikt6 != value))
				{
					this.OnPikt6Changing(value);
					this.SendPropertyChanging();
					this._Pikt6 = value;
					this.SendPropertyChanged("Pikt6");
					this.OnPikt6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt6_Opis", DbType="NVarChar(10)")]
		public string Pikt6_Opis
		{
			get
			{
				return this._Pikt6_Opis;
			}
			set
			{
				if ((this._Pikt6_Opis != value))
				{
					this.OnPikt6_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt6_Opis = value;
					this.SendPropertyChanged("Pikt6_Opis");
					this.OnPikt6_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt7", DbType="NVarChar(7)")]
		public string Pikt7
		{
			get
			{
				return this._Pikt7;
			}
			set
			{
				if ((this._Pikt7 != value))
				{
					this.OnPikt7Changing(value);
					this.SendPropertyChanging();
					this._Pikt7 = value;
					this.SendPropertyChanged("Pikt7");
					this.OnPikt7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt7_Opis", DbType="NVarChar(10)")]
		public string Pikt7_Opis
		{
			get
			{
				return this._Pikt7_Opis;
			}
			set
			{
				if ((this._Pikt7_Opis != value))
				{
					this.OnPikt7_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt7_Opis = value;
					this.SendPropertyChanged("Pikt7_Opis");
					this.OnPikt7_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt8", DbType="NVarChar(7)")]
		public string Pikt8
		{
			get
			{
				return this._Pikt8;
			}
			set
			{
				if ((this._Pikt8 != value))
				{
					this.OnPikt8Changing(value);
					this.SendPropertyChanging();
					this._Pikt8 = value;
					this.SendPropertyChanged("Pikt8");
					this.OnPikt8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt8_Opis", DbType="NVarChar(10)")]
		public string Pikt8_Opis
		{
			get
			{
				return this._Pikt8_Opis;
			}
			set
			{
				if ((this._Pikt8_Opis != value))
				{
					this.OnPikt8_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt8_Opis = value;
					this.SendPropertyChanged("Pikt8_Opis");
					this.OnPikt8_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt9", DbType="NVarChar(7)")]
		public string Pikt9
		{
			get
			{
				return this._Pikt9;
			}
			set
			{
				if ((this._Pikt9 != value))
				{
					this.OnPikt9Changing(value);
					this.SendPropertyChanging();
					this._Pikt9 = value;
					this.SendPropertyChanged("Pikt9");
					this.OnPikt9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt9_Opis", DbType="NVarChar(10)")]
		public string Pikt9_Opis
		{
			get
			{
				return this._Pikt9_Opis;
			}
			set
			{
				if ((this._Pikt9_Opis != value))
				{
					this.OnPikt9_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt9_Opis = value;
					this.SendPropertyChanged("Pikt9_Opis");
					this.OnPikt9_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt10", DbType="NVarChar(7)")]
		public string Pikt10
		{
			get
			{
				return this._Pikt10;
			}
			set
			{
				if ((this._Pikt10 != value))
				{
					this.OnPikt10Changing(value);
					this.SendPropertyChanging();
					this._Pikt10 = value;
					this.SendPropertyChanged("Pikt10");
					this.OnPikt10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt10_Opis", DbType="NVarChar(10)")]
		public string Pikt10_Opis
		{
			get
			{
				return this._Pikt10_Opis;
			}
			set
			{
				if ((this._Pikt10_Opis != value))
				{
					this.OnPikt10_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt10_Opis = value;
					this.SendPropertyChanged("Pikt10_Opis");
					this.OnPikt10_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt11", DbType="NVarChar(7)")]
		public string Pikt11
		{
			get
			{
				return this._Pikt11;
			}
			set
			{
				if ((this._Pikt11 != value))
				{
					this.OnPikt11Changing(value);
					this.SendPropertyChanging();
					this._Pikt11 = value;
					this.SendPropertyChanged("Pikt11");
					this.OnPikt11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt11_Opis", DbType="NVarChar(10)")]
		public string Pikt11_Opis
		{
			get
			{
				return this._Pikt11_Opis;
			}
			set
			{
				if ((this._Pikt11_Opis != value))
				{
					this.OnPikt11_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt11_Opis = value;
					this.SendPropertyChanged("Pikt11_Opis");
					this.OnPikt11_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt12", DbType="NVarChar(7)")]
		public string Pikt12
		{
			get
			{
				return this._Pikt12;
			}
			set
			{
				if ((this._Pikt12 != value))
				{
					this.OnPikt12Changing(value);
					this.SendPropertyChanging();
					this._Pikt12 = value;
					this.SendPropertyChanged("Pikt12");
					this.OnPikt12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pikt12_Opis", DbType="NVarChar(10)")]
		public string Pikt12_Opis
		{
			get
			{
				return this._Pikt12_Opis;
			}
			set
			{
				if ((this._Pikt12_Opis != value))
				{
					this.OnPikt12_OpisChanging(value);
					this.SendPropertyChanging();
					this._Pikt12_Opis = value;
					this.SendPropertyChanged("Pikt12_Opis");
					this.OnPikt12_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CennikLiczbaKolumn", DbType="Int")]
		public System.Nullable<int> CennikLiczbaKolumn
		{
			get
			{
				return this._CennikLiczbaKolumn;
			}
			set
			{
				if ((this._CennikLiczbaKolumn != value))
				{
					this.OnCennikLiczbaKolumnChanging(value);
					this.SendPropertyChanging();
					this._CennikLiczbaKolumn = value;
					this.SendPropertyChanged("CennikLiczbaKolumn");
					this.OnCennikLiczbaKolumnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_GB_Rough", DbType="NVarChar(150)")]
		public string Nazwa_GB_Rough
		{
			get
			{
				return this._Nazwa_GB_Rough;
			}
			set
			{
				if ((this._Nazwa_GB_Rough != value))
				{
					this.OnNazwa_GB_RoughChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_GB_Rough = value;
					this.SendPropertyChanged("Nazwa_GB_Rough");
					this.OnNazwa_GB_RoughChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_D_Rough", DbType="NVarChar(150)")]
		public string Nazwa_D_Rough
		{
			get
			{
				return this._Nazwa_D_Rough;
			}
			set
			{
				if ((this._Nazwa_D_Rough != value))
				{
					this.OnNazwa_D_RoughChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_D_Rough = value;
					this.SendPropertyChanged("Nazwa_D_Rough");
					this.OnNazwa_D_RoughChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_F_Rough", DbType="NVarChar(150)")]
		public string Nazwa_F_Rough
		{
			get
			{
				return this._Nazwa_F_Rough;
			}
			set
			{
				if ((this._Nazwa_F_Rough != value))
				{
					this.OnNazwa_F_RoughChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_F_Rough = value;
					this.SendPropertyChanged("Nazwa_F_Rough");
					this.OnNazwa_F_RoughChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_ES_Rough", DbType="NVarChar(150)")]
		public string Nazwa_ES_Rough
		{
			get
			{
				return this._Nazwa_ES_Rough;
			}
			set
			{
				if ((this._Nazwa_ES_Rough != value))
				{
					this.OnNazwa_ES_RoughChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_ES_Rough = value;
					this.SendPropertyChanged("Nazwa_ES_Rough");
					this.OnNazwa_ES_RoughChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_IT_Rough", DbType="NVarChar(150)")]
		public string Nazwa_IT_Rough
		{
			get
			{
				return this._Nazwa_IT_Rough;
			}
			set
			{
				if ((this._Nazwa_IT_Rough != value))
				{
					this.OnNazwa_IT_RoughChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_IT_Rough = value;
					this.SendPropertyChanged("Nazwa_IT_Rough");
					this.OnNazwa_IT_RoughChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_CZ_Rough", DbType="NVarChar(150)")]
		public string Nazwa_CZ_Rough
		{
			get
			{
				return this._Nazwa_CZ_Rough;
			}
			set
			{
				if ((this._Nazwa_CZ_Rough != value))
				{
					this.OnNazwa_CZ_RoughChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_CZ_Rough = value;
					this.SendPropertyChanged("Nazwa_CZ_Rough");
					this.OnNazwa_CZ_RoughChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_SK_Rough", DbType="NVarChar(150)")]
		public string Nazwa_SK_Rough
		{
			get
			{
				return this._Nazwa_SK_Rough;
			}
			set
			{
				if ((this._Nazwa_SK_Rough != value))
				{
					this.OnNazwa_SK_RoughChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_SK_Rough = value;
					this.SendPropertyChanged("Nazwa_SK_Rough");
					this.OnNazwa_SK_RoughChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_RUS_Rough", DbType="NVarChar(150)")]
		public string Nazwa_RUS_Rough
		{
			get
			{
				return this._Nazwa_RUS_Rough;
			}
			set
			{
				if ((this._Nazwa_RUS_Rough != value))
				{
					this.OnNazwa_RUS_RoughChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_RUS_Rough = value;
					this.SendPropertyChanged("Nazwa_RUS_Rough");
					this.OnNazwa_RUS_RoughChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_PL_Rough", DbType="NVarChar(150)")]
		public string Nazwa_PL_Rough
		{
			get
			{
				return this._Nazwa_PL_Rough;
			}
			set
			{
				if ((this._Nazwa_PL_Rough != value))
				{
					this.OnNazwa_PL_RoughChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_PL_Rough = value;
					this.SendPropertyChanged("Nazwa_PL_Rough");
					this.OnNazwa_PL_RoughChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_GB_1", DbType="NVarChar(150)")]
		public string Nazwa_GB_1
		{
			get
			{
				return this._Nazwa_GB_1;
			}
			set
			{
				if ((this._Nazwa_GB_1 != value))
				{
					this.OnNazwa_GB_1Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_GB_1 = value;
					this.SendPropertyChanged("Nazwa_GB_1");
					this.OnNazwa_GB_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_D_1", DbType="NVarChar(150)")]
		public string Nazwa_D_1
		{
			get
			{
				return this._Nazwa_D_1;
			}
			set
			{
				if ((this._Nazwa_D_1 != value))
				{
					this.OnNazwa_D_1Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_D_1 = value;
					this.SendPropertyChanged("Nazwa_D_1");
					this.OnNazwa_D_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_F_1", DbType="NVarChar(150)")]
		public string Nazwa_F_1
		{
			get
			{
				return this._Nazwa_F_1;
			}
			set
			{
				if ((this._Nazwa_F_1 != value))
				{
					this.OnNazwa_F_1Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_F_1 = value;
					this.SendPropertyChanged("Nazwa_F_1");
					this.OnNazwa_F_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_ES_1", DbType="NVarChar(150)")]
		public string Nazwa_ES_1
		{
			get
			{
				return this._Nazwa_ES_1;
			}
			set
			{
				if ((this._Nazwa_ES_1 != value))
				{
					this.OnNazwa_ES_1Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_ES_1 = value;
					this.SendPropertyChanged("Nazwa_ES_1");
					this.OnNazwa_ES_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_IT_1", DbType="NVarChar(150)")]
		public string Nazwa_IT_1
		{
			get
			{
				return this._Nazwa_IT_1;
			}
			set
			{
				if ((this._Nazwa_IT_1 != value))
				{
					this.OnNazwa_IT_1Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_IT_1 = value;
					this.SendPropertyChanged("Nazwa_IT_1");
					this.OnNazwa_IT_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_CZ_1", DbType="NVarChar(150)")]
		public string Nazwa_CZ_1
		{
			get
			{
				return this._Nazwa_CZ_1;
			}
			set
			{
				if ((this._Nazwa_CZ_1 != value))
				{
					this.OnNazwa_CZ_1Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_CZ_1 = value;
					this.SendPropertyChanged("Nazwa_CZ_1");
					this.OnNazwa_CZ_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_SK_1", DbType="NVarChar(150)")]
		public string Nazwa_SK_1
		{
			get
			{
				return this._Nazwa_SK_1;
			}
			set
			{
				if ((this._Nazwa_SK_1 != value))
				{
					this.OnNazwa_SK_1Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_SK_1 = value;
					this.SendPropertyChanged("Nazwa_SK_1");
					this.OnNazwa_SK_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_RUS_1", DbType="NVarChar(150)")]
		public string Nazwa_RUS_1
		{
			get
			{
				return this._Nazwa_RUS_1;
			}
			set
			{
				if ((this._Nazwa_RUS_1 != value))
				{
					this.OnNazwa_RUS_1Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_RUS_1 = value;
					this.SendPropertyChanged("Nazwa_RUS_1");
					this.OnNazwa_RUS_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_PL_1", DbType="NVarChar(150)")]
		public string Nazwa_PL_1
		{
			get
			{
				return this._Nazwa_PL_1;
			}
			set
			{
				if ((this._Nazwa_PL_1 != value))
				{
					this.OnNazwa_PL_1Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_PL_1 = value;
					this.SendPropertyChanged("Nazwa_PL_1");
					this.OnNazwa_PL_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_GB_2", DbType="NVarChar(150)")]
		public string Nazwa_GB_2
		{
			get
			{
				return this._Nazwa_GB_2;
			}
			set
			{
				if ((this._Nazwa_GB_2 != value))
				{
					this.OnNazwa_GB_2Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_GB_2 = value;
					this.SendPropertyChanged("Nazwa_GB_2");
					this.OnNazwa_GB_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_D_2", DbType="NVarChar(150)")]
		public string Nazwa_D_2
		{
			get
			{
				return this._Nazwa_D_2;
			}
			set
			{
				if ((this._Nazwa_D_2 != value))
				{
					this.OnNazwa_D_2Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_D_2 = value;
					this.SendPropertyChanged("Nazwa_D_2");
					this.OnNazwa_D_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_F_2", DbType="NVarChar(150)")]
		public string Nazwa_F_2
		{
			get
			{
				return this._Nazwa_F_2;
			}
			set
			{
				if ((this._Nazwa_F_2 != value))
				{
					this.OnNazwa_F_2Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_F_2 = value;
					this.SendPropertyChanged("Nazwa_F_2");
					this.OnNazwa_F_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_ES_2", DbType="NVarChar(150)")]
		public string Nazwa_ES_2
		{
			get
			{
				return this._Nazwa_ES_2;
			}
			set
			{
				if ((this._Nazwa_ES_2 != value))
				{
					this.OnNazwa_ES_2Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_ES_2 = value;
					this.SendPropertyChanged("Nazwa_ES_2");
					this.OnNazwa_ES_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_IT_2", DbType="NVarChar(150)")]
		public string Nazwa_IT_2
		{
			get
			{
				return this._Nazwa_IT_2;
			}
			set
			{
				if ((this._Nazwa_IT_2 != value))
				{
					this.OnNazwa_IT_2Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_IT_2 = value;
					this.SendPropertyChanged("Nazwa_IT_2");
					this.OnNazwa_IT_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_CZ_2", DbType="NVarChar(150)")]
		public string Nazwa_CZ_2
		{
			get
			{
				return this._Nazwa_CZ_2;
			}
			set
			{
				if ((this._Nazwa_CZ_2 != value))
				{
					this.OnNazwa_CZ_2Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_CZ_2 = value;
					this.SendPropertyChanged("Nazwa_CZ_2");
					this.OnNazwa_CZ_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_SK_2", DbType="NVarChar(150)")]
		public string Nazwa_SK_2
		{
			get
			{
				return this._Nazwa_SK_2;
			}
			set
			{
				if ((this._Nazwa_SK_2 != value))
				{
					this.OnNazwa_SK_2Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_SK_2 = value;
					this.SendPropertyChanged("Nazwa_SK_2");
					this.OnNazwa_SK_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_RUS_2", DbType="NVarChar(150)")]
		public string Nazwa_RUS_2
		{
			get
			{
				return this._Nazwa_RUS_2;
			}
			set
			{
				if ((this._Nazwa_RUS_2 != value))
				{
					this.OnNazwa_RUS_2Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_RUS_2 = value;
					this.SendPropertyChanged("Nazwa_RUS_2");
					this.OnNazwa_RUS_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_PL_2", DbType="NVarChar(150)")]
		public string Nazwa_PL_2
		{
			get
			{
				return this._Nazwa_PL_2;
			}
			set
			{
				if ((this._Nazwa_PL_2 != value))
				{
					this.OnNazwa_PL_2Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_PL_2 = value;
					this.SendPropertyChanged("Nazwa_PL_2");
					this.OnNazwa_PL_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_GB_3", DbType="NVarChar(150)")]
		public string Nazwa_GB_3
		{
			get
			{
				return this._Nazwa_GB_3;
			}
			set
			{
				if ((this._Nazwa_GB_3 != value))
				{
					this.OnNazwa_GB_3Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_GB_3 = value;
					this.SendPropertyChanged("Nazwa_GB_3");
					this.OnNazwa_GB_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_D_3", DbType="NVarChar(150)")]
		public string Nazwa_D_3
		{
			get
			{
				return this._Nazwa_D_3;
			}
			set
			{
				if ((this._Nazwa_D_3 != value))
				{
					this.OnNazwa_D_3Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_D_3 = value;
					this.SendPropertyChanged("Nazwa_D_3");
					this.OnNazwa_D_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_F_3", DbType="NVarChar(150)")]
		public string Nazwa_F_3
		{
			get
			{
				return this._Nazwa_F_3;
			}
			set
			{
				if ((this._Nazwa_F_3 != value))
				{
					this.OnNazwa_F_3Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_F_3 = value;
					this.SendPropertyChanged("Nazwa_F_3");
					this.OnNazwa_F_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_ES_3", DbType="NVarChar(150)")]
		public string Nazwa_ES_3
		{
			get
			{
				return this._Nazwa_ES_3;
			}
			set
			{
				if ((this._Nazwa_ES_3 != value))
				{
					this.OnNazwa_ES_3Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_ES_3 = value;
					this.SendPropertyChanged("Nazwa_ES_3");
					this.OnNazwa_ES_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_IT_3", DbType="NVarChar(150)")]
		public string Nazwa_IT_3
		{
			get
			{
				return this._Nazwa_IT_3;
			}
			set
			{
				if ((this._Nazwa_IT_3 != value))
				{
					this.OnNazwa_IT_3Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_IT_3 = value;
					this.SendPropertyChanged("Nazwa_IT_3");
					this.OnNazwa_IT_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_CZ_3", DbType="NVarChar(150)")]
		public string Nazwa_CZ_3
		{
			get
			{
				return this._Nazwa_CZ_3;
			}
			set
			{
				if ((this._Nazwa_CZ_3 != value))
				{
					this.OnNazwa_CZ_3Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_CZ_3 = value;
					this.SendPropertyChanged("Nazwa_CZ_3");
					this.OnNazwa_CZ_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_SK_3", DbType="NVarChar(150)")]
		public string Nazwa_SK_3
		{
			get
			{
				return this._Nazwa_SK_3;
			}
			set
			{
				if ((this._Nazwa_SK_3 != value))
				{
					this.OnNazwa_SK_3Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_SK_3 = value;
					this.SendPropertyChanged("Nazwa_SK_3");
					this.OnNazwa_SK_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_RUS_3", DbType="NVarChar(150)")]
		public string Nazwa_RUS_3
		{
			get
			{
				return this._Nazwa_RUS_3;
			}
			set
			{
				if ((this._Nazwa_RUS_3 != value))
				{
					this.OnNazwa_RUS_3Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_RUS_3 = value;
					this.SendPropertyChanged("Nazwa_RUS_3");
					this.OnNazwa_RUS_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_PL_3", DbType="NVarChar(150)")]
		public string Nazwa_PL_3
		{
			get
			{
				return this._Nazwa_PL_3;
			}
			set
			{
				if ((this._Nazwa_PL_3 != value))
				{
					this.OnNazwa_PL_3Changing(value);
					this.SendPropertyChanging();
					this._Nazwa_PL_3 = value;
					this.SendPropertyChanged("Nazwa_PL_3");
					this.OnNazwa_PL_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zweryfikowano_Ikonki", DbType="NVarChar(3)")]
		public string Zweryfikowano_Ikonki
		{
			get
			{
				return this._Zweryfikowano_Ikonki;
			}
			set
			{
				if ((this._Zweryfikowano_Ikonki != value))
				{
					this.OnZweryfikowano_IkonkiChanging(value);
					this.SendPropertyChanging();
					this._Zweryfikowano_Ikonki = value;
					this.SendPropertyChanged("Zweryfikowano_Ikonki");
					this.OnZweryfikowano_IkonkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RysunekSzlif", DbType="NVarChar(50)")]
		public string RysunekSzlif
		{
			get
			{
				return this._RysunekSzlif;
			}
			set
			{
				if ((this._RysunekSzlif != value))
				{
					this.OnRysunekSzlifChanging(value);
					this.SendPropertyChanging();
					this._RysunekSzlif = value;
					this.SendPropertyChanged("RysunekSzlif");
					this.OnRysunekSzlifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Archiwum", DbType="Bit")]
		public System.Nullable<bool> Archiwum
		{
			get
			{
				return this._Archiwum;
			}
			set
			{
				if ((this._Archiwum != value))
				{
					this.OnArchiwumChanging(value);
					this.SendPropertyChanging();
					this._Archiwum = value;
					this.SendPropertyChanged("Archiwum");
					this.OnArchiwumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Karta zmian norm pracy_kopia_zła]")]
	public partial class Karta_zmian_norm_pracy_kopia_zła : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NrKartyZmian;
		
		private string _Wydział;
		
		private System.Nullable<System.DateTime> _DataZmiany;
		
		private string _PodstawaZmiany;
		
		private string _Wystawił;
		
		private System.Nullable<System.DateTime> _DataWystawienia;
		
		private string _Zatwierdził;
		
		private System.Nullable<System.DateTime> _DataZatwierdzenia;
		
		private System.Nullable<System.DateTime> _DataWprowadzenia;
		
		private System.Nullable<bool> _ZmienionoWJDE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNrKartyZmianChanging(string value);
    partial void OnNrKartyZmianChanged();
    partial void OnWydziałChanging(string value);
    partial void OnWydziałChanged();
    partial void OnDataZmianyChanging(System.Nullable<System.DateTime> value);
    partial void OnDataZmianyChanged();
    partial void OnPodstawaZmianyChanging(string value);
    partial void OnPodstawaZmianyChanged();
    partial void OnWystawiłChanging(string value);
    partial void OnWystawiłChanged();
    partial void OnDataWystawieniaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataWystawieniaChanged();
    partial void OnZatwierdziłChanging(string value);
    partial void OnZatwierdziłChanged();
    partial void OnDataZatwierdzeniaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataZatwierdzeniaChanged();
    partial void OnDataWprowadzeniaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataWprowadzeniaChanged();
    partial void OnZmienionoWJDEChanging(System.Nullable<bool> value);
    partial void OnZmienionoWJDEChanged();
    #endregion
		
		public Karta_zmian_norm_pracy_kopia_zła()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrKartyZmian", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NrKartyZmian
		{
			get
			{
				return this._NrKartyZmian;
			}
			set
			{
				if ((this._NrKartyZmian != value))
				{
					this.OnNrKartyZmianChanging(value);
					this.SendPropertyChanging();
					this._NrKartyZmian = value;
					this.SendPropertyChanged("NrKartyZmian");
					this.OnNrKartyZmianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wydział", DbType="NVarChar(50)")]
		public string Wydział
		{
			get
			{
				return this._Wydział;
			}
			set
			{
				if ((this._Wydział != value))
				{
					this.OnWydziałChanging(value);
					this.SendPropertyChanging();
					this._Wydział = value;
					this.SendPropertyChanged("Wydział");
					this.OnWydziałChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataZmiany", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataZmiany
		{
			get
			{
				return this._DataZmiany;
			}
			set
			{
				if ((this._DataZmiany != value))
				{
					this.OnDataZmianyChanging(value);
					this.SendPropertyChanging();
					this._DataZmiany = value;
					this.SendPropertyChanged("DataZmiany");
					this.OnDataZmianyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PodstawaZmiany", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string PodstawaZmiany
		{
			get
			{
				return this._PodstawaZmiany;
			}
			set
			{
				if ((this._PodstawaZmiany != value))
				{
					this.OnPodstawaZmianyChanging(value);
					this.SendPropertyChanging();
					this._PodstawaZmiany = value;
					this.SendPropertyChanged("PodstawaZmiany");
					this.OnPodstawaZmianyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wystawił", DbType="NVarChar(50)")]
		public string Wystawił
		{
			get
			{
				return this._Wystawił;
			}
			set
			{
				if ((this._Wystawił != value))
				{
					this.OnWystawiłChanging(value);
					this.SendPropertyChanging();
					this._Wystawił = value;
					this.SendPropertyChanged("Wystawił");
					this.OnWystawiłChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataWystawienia", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataWystawienia
		{
			get
			{
				return this._DataWystawienia;
			}
			set
			{
				if ((this._DataWystawienia != value))
				{
					this.OnDataWystawieniaChanging(value);
					this.SendPropertyChanging();
					this._DataWystawienia = value;
					this.SendPropertyChanged("DataWystawienia");
					this.OnDataWystawieniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zatwierdził", DbType="NVarChar(50)")]
		public string Zatwierdził
		{
			get
			{
				return this._Zatwierdził;
			}
			set
			{
				if ((this._Zatwierdził != value))
				{
					this.OnZatwierdziłChanging(value);
					this.SendPropertyChanging();
					this._Zatwierdził = value;
					this.SendPropertyChanged("Zatwierdził");
					this.OnZatwierdziłChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataZatwierdzenia", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataZatwierdzenia
		{
			get
			{
				return this._DataZatwierdzenia;
			}
			set
			{
				if ((this._DataZatwierdzenia != value))
				{
					this.OnDataZatwierdzeniaChanging(value);
					this.SendPropertyChanging();
					this._DataZatwierdzenia = value;
					this.SendPropertyChanged("DataZatwierdzenia");
					this.OnDataZatwierdzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataWprowadzenia", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataWprowadzenia
		{
			get
			{
				return this._DataWprowadzenia;
			}
			set
			{
				if ((this._DataWprowadzenia != value))
				{
					this.OnDataWprowadzeniaChanging(value);
					this.SendPropertyChanging();
					this._DataWprowadzenia = value;
					this.SendPropertyChanged("DataWprowadzenia");
					this.OnDataWprowadzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZmienionoWJDE", DbType="Bit")]
		public System.Nullable<bool> ZmienionoWJDE
		{
			get
			{
				return this._ZmienionoWJDE;
			}
			set
			{
				if ((this._ZmienionoWJDE != value))
				{
					this.OnZmienionoWJDEChanging(value);
					this.SendPropertyChanging();
					this._ZmienionoWJDE = value;
					this.SendPropertyChanged("ZmienionoWJDE");
					this.OnZmienionoWJDEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
