#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_SharePoint
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KARTY_PRODUKCJI")]
	public partial class baza_metekDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMetki_PDF(Metki_PDF instance);
    partial void UpdateMetki_PDF(Metki_PDF instance);
    partial void DeleteMetki_PDF(Metki_PDF instance);
    partial void InsertMetki_baza(Metki_baza instance);
    partial void UpdateMetki_baza(Metki_baza instance);
    partial void DeleteMetki_baza(Metki_baza instance);
    partial void InsertGAL_POWIERZCHNIE(GAL_POWIERZCHNIE instance);
    partial void UpdateGAL_POWIERZCHNIE(GAL_POWIERZCHNIE instance);
    partial void DeleteGAL_POWIERZCHNIE(GAL_POWIERZCHNIE instance);
    partial void InsertSzlifiernia_operacje_skan(Szlifiernia_operacje_skan instance);
    partial void UpdateSzlifiernia_operacje_skan(Szlifiernia_operacje_skan instance);
    partial void DeleteSzlifiernia_operacje_skan(Szlifiernia_operacje_skan instance);
    #endregion
		
		public baza_metekDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["KARTY_PRODUKCJIConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public baza_metekDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baza_metekDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baza_metekDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baza_metekDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Metki_PDF> Metki_PDFs
		{
			get
			{
				return this.GetTable<Metki_PDF>();
			}
		}
		
		public System.Data.Linq.Table<Metki_baza> Metki_bazas
		{
			get
			{
				return this.GetTable<Metki_baza>();
			}
		}
		
		public System.Data.Linq.Table<GAL_kolory_kodow> GAL_kolory_kodows
		{
			get
			{
				return this.GetTable<GAL_kolory_kodow>();
			}
		}
		
		public System.Data.Linq.Table<GAL_POWIERZCHNIE> GAL_POWIERZCHNIEs
		{
			get
			{
				return this.GetTable<GAL_POWIERZCHNIE>();
			}
		}
		
		public System.Data.Linq.Table<Marszruta> Marszruta
		{
			get
			{
				return this.GetTable<Marszruta>();
			}
		}
		
		public System.Data.Linq.Table<Marszruty_szlif> Marszruty_szlif
		{
			get
			{
				return this.GetTable<Marszruty_szlif>();
			}
		}
		
		public System.Data.Linq.Table<Szlifiernia_operacje_skan> Szlifiernia_operacje_skan
		{
			get
			{
				return this.GetTable<Szlifiernia_operacje_skan>();
			}
		}
		
		public System.Data.Linq.Table<Wykonanie_szlifiernia_normas> Wykonanie_szlifiernia_normas
		{
			get
			{
				return this.GetTable<Wykonanie_szlifiernia_normas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Metki_PDF")]
	public partial class Metki_PDF : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nr_zlecenia;
		
		private System.Data.Linq.Binary _PDF;
		
		private System.Nullable<System.DateTime> _Data_utw;
		
		private System.Nullable<int> _Ilosc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNr_zleceniaChanging(string value);
    partial void OnNr_zleceniaChanged();
    partial void OnPDFChanging(System.Data.Linq.Binary value);
    partial void OnPDFChanged();
    partial void OnData_utwChanging(System.Nullable<System.DateTime> value);
    partial void OnData_utwChanged();
    partial void OnIloscChanging(System.Nullable<int> value);
    partial void OnIloscChanged();
    #endregion
		
		public Metki_PDF()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_zlecenia", DbType="NVarChar(50)")]
		public string Nr_zlecenia
		{
			get
			{
				return this._Nr_zlecenia;
			}
			set
			{
				if ((this._Nr_zlecenia != value))
				{
					this.OnNr_zleceniaChanging(value);
					this.SendPropertyChanging();
					this._Nr_zlecenia = value;
					this.SendPropertyChanged("Nr_zlecenia");
					this.OnNr_zleceniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDF", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PDF
		{
			get
			{
				return this._PDF;
			}
			set
			{
				if ((this._PDF != value))
				{
					this.OnPDFChanging(value);
					this.SendPropertyChanging();
					this._PDF = value;
					this.SendPropertyChanged("PDF");
					this.OnPDFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_utw", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data_utw
		{
			get
			{
				return this._Data_utw;
			}
			set
			{
				if ((this._Data_utw != value))
				{
					this.OnData_utwChanging(value);
					this.SendPropertyChanging();
					this._Data_utw = value;
					this.SendPropertyChanged("Data_utw");
					this.OnData_utwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc", DbType="Int")]
		public System.Nullable<int> Ilosc
		{
			get
			{
				return this._Ilosc;
			}
			set
			{
				if ((this._Ilosc != value))
				{
					this.OnIloscChanging(value);
					this.SendPropertyChanging();
					this._Ilosc = value;
					this.SendPropertyChanged("Ilosc");
					this.OnIloscChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Metki_")]
	public partial class Metki_baza : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nr_zlecenia;
		
		private string _Nr_kodu;
		
		private string _User_id;
		
		private System.Nullable<System.DateTime> _Data_utw;
		
		private System.Nullable<int> _Ilosc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNr_zleceniaChanging(string value);
    partial void OnNr_zleceniaChanged();
    partial void OnNr_koduChanging(string value);
    partial void OnNr_koduChanged();
    partial void OnUser_idChanging(string value);
    partial void OnUser_idChanged();
    partial void OnData_utwChanging(System.Nullable<System.DateTime> value);
    partial void OnData_utwChanged();
    partial void OnIloscChanging(System.Nullable<int> value);
    partial void OnIloscChanged();
    #endregion
		
		public Metki_baza()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_zlecenia", DbType="NVarChar(50)")]
		public string Nr_zlecenia
		{
			get
			{
				return this._Nr_zlecenia;
			}
			set
			{
				if ((this._Nr_zlecenia != value))
				{
					this.OnNr_zleceniaChanging(value);
					this.SendPropertyChanging();
					this._Nr_zlecenia = value;
					this.SendPropertyChanged("Nr_zlecenia");
					this.OnNr_zleceniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_kodu", DbType="NVarChar(50)")]
		public string Nr_kodu
		{
			get
			{
				return this._Nr_kodu;
			}
			set
			{
				if ((this._Nr_kodu != value))
				{
					this.OnNr_koduChanging(value);
					this.SendPropertyChanging();
					this._Nr_kodu = value;
					this.SendPropertyChanged("Nr_kodu");
					this.OnNr_koduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_id", DbType="NVarChar(50)")]
		public string User_id
		{
			get
			{
				return this._User_id;
			}
			set
			{
				if ((this._User_id != value))
				{
					this.OnUser_idChanging(value);
					this.SendPropertyChanging();
					this._User_id = value;
					this.SendPropertyChanged("User_id");
					this.OnUser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_utw", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data_utw
		{
			get
			{
				return this._Data_utw;
			}
			set
			{
				if ((this._Data_utw != value))
				{
					this.OnData_utwChanging(value);
					this.SendPropertyChanging();
					this._Data_utw = value;
					this.SendPropertyChanged("Data_utw");
					this.OnData_utwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc", DbType="Int")]
		public System.Nullable<int> Ilosc
		{
			get
			{
				return this._Ilosc;
			}
			set
			{
				if ((this._Ilosc != value))
				{
					this.OnIloscChanging(value);
					this.SendPropertyChanging();
					this._Ilosc = value;
					this.SendPropertyChanged("Ilosc");
					this.OnIloscChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GAL_kolory_kodow")]
	public partial class GAL_kolory_kodow
	{
		
		private double _ID_WYR;
		
		private string _KOD_WYROBU;
		
		private string _OPIS;
		
		private string _KOLOR;
		
		private string _NR_RYSUNKU;
		
		private string _KOD_PO_WYKONCZENIU;
		
		public GAL_kolory_kodow()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_WYR", DbType="Float NOT NULL")]
		public double ID_WYR
		{
			get
			{
				return this._ID_WYR;
			}
			set
			{
				if ((this._ID_WYR != value))
				{
					this._ID_WYR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOD_WYROBU", DbType="NChar(25)")]
		public string KOD_WYROBU
		{
			get
			{
				return this._KOD_WYROBU;
			}
			set
			{
				if ((this._KOD_WYROBU != value))
				{
					this._KOD_WYROBU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPIS", DbType="NChar(60) NOT NULL", CanBeNull=false)]
		public string OPIS
		{
			get
			{
				return this._OPIS;
			}
			set
			{
				if ((this._OPIS != value))
				{
					this._OPIS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOLOR", DbType="NChar(30)")]
		public string KOLOR
		{
			get
			{
				return this._KOLOR;
			}
			set
			{
				if ((this._KOLOR != value))
				{
					this._KOLOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_RYSUNKU", DbType="NChar(10)")]
		public string NR_RYSUNKU
		{
			get
			{
				return this._NR_RYSUNKU;
			}
			set
			{
				if ((this._NR_RYSUNKU != value))
				{
					this._NR_RYSUNKU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOD_PO_WYKONCZENIU", DbType="NChar(25)")]
		public string KOD_PO_WYKONCZENIU
		{
			get
			{
				return this._KOD_PO_WYKONCZENIU;
			}
			set
			{
				if ((this._KOD_PO_WYKONCZENIU != value))
				{
					this._KOD_PO_WYKONCZENIU = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GAL_POWIERZCHNIE")]
	public partial class GAL_POWIERZCHNIE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NR_RYS;
		
		private System.Nullable<double> _POW;
		
		private System.Nullable<bool> _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNR_RYSChanging(string value);
    partial void OnNR_RYSChanged();
    partial void OnPOWChanging(System.Nullable<double> value);
    partial void OnPOWChanged();
    partial void OnSTATUSChanging(System.Nullable<bool> value);
    partial void OnSTATUSChanged();
    #endregion
		
		public GAL_POWIERZCHNIE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_RYS", DbType="NVarChar(50)")]
		public string NR_RYS
		{
			get
			{
				return this._NR_RYS;
			}
			set
			{
				if ((this._NR_RYS != value))
				{
					this.OnNR_RYSChanging(value);
					this.SendPropertyChanging();
					this._NR_RYS = value;
					this.SendPropertyChanged("NR_RYS");
					this.OnNR_RYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POW", DbType="Float")]
		public System.Nullable<double> POW
		{
			get
			{
				return this._POW;
			}
			set
			{
				if ((this._POW != value))
				{
					this.OnPOWChanging(value);
					this.SendPropertyChanging();
					this._POW = value;
					this.SendPropertyChanged("POW");
					this.OnPOWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Bit")]
		public System.Nullable<bool> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marszruta")]
	public partial class Marszruta
	{
		
		private string _kod2;
		
		private string _Nazwa_wyrobu;
		
		private string _Id_wyrobu;
		
		private string _Kolor;
		
		private System.Nullable<int> _Nr_grupy;
		
		private string _Standard;
		
		private System.Nullable<double> _KodOperacji;
		
		private string _CentrumRobocze;
		
		private System.Nullable<double> _Nr_kol_operacji;
		
		private string _Typ;
		
		private System.Nullable<int> _IloscSztZm;
		
		private System.Nullable<System.DateTime> _DataWprowadzenia;
		
		private System.Nullable<System.DateTime> _ObowiązujeOd;
		
		private System.Nullable<System.DateTime> _ObowiązujeDo;
		
		public Marszruta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod2", DbType="NVarChar(50)")]
		public string kod2
		{
			get
			{
				return this._kod2;
			}
			set
			{
				if ((this._kod2 != value))
				{
					this._kod2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_wyrobu", DbType="NVarChar(50)")]
		public string Nazwa_wyrobu
		{
			get
			{
				return this._Nazwa_wyrobu;
			}
			set
			{
				if ((this._Nazwa_wyrobu != value))
				{
					this._Nazwa_wyrobu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_wyrobu", DbType="NVarChar(255)")]
		public string Id_wyrobu
		{
			get
			{
				return this._Id_wyrobu;
			}
			set
			{
				if ((this._Id_wyrobu != value))
				{
					this._Id_wyrobu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kolor", DbType="NVarChar(50)")]
		public string Kolor
		{
			get
			{
				return this._Kolor;
			}
			set
			{
				if ((this._Kolor != value))
				{
					this._Kolor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_grupy", DbType="Int")]
		public System.Nullable<int> Nr_grupy
		{
			get
			{
				return this._Nr_grupy;
			}
			set
			{
				if ((this._Nr_grupy != value))
				{
					this._Nr_grupy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Standard", DbType="NVarChar(50)")]
		public string Standard
		{
			get
			{
				return this._Standard;
			}
			set
			{
				if ((this._Standard != value))
				{
					this._Standard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodOperacji", DbType="Float")]
		public System.Nullable<double> KodOperacji
		{
			get
			{
				return this._KodOperacji;
			}
			set
			{
				if ((this._KodOperacji != value))
				{
					this._KodOperacji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentrumRobocze", DbType="NVarChar(255)")]
		public string CentrumRobocze
		{
			get
			{
				return this._CentrumRobocze;
			}
			set
			{
				if ((this._CentrumRobocze != value))
				{
					this._CentrumRobocze = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nr kol operacji]", Storage="_Nr_kol_operacji", DbType="Float")]
		public System.Nullable<double> Nr_kol_operacji
		{
			get
			{
				return this._Nr_kol_operacji;
			}
			set
			{
				if ((this._Nr_kol_operacji != value))
				{
					this._Nr_kol_operacji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Typ", DbType="NVarChar(1)")]
		public string Typ
		{
			get
			{
				return this._Typ;
			}
			set
			{
				if ((this._Typ != value))
				{
					this._Typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IloscSztZm", DbType="Int")]
		public System.Nullable<int> IloscSztZm
		{
			get
			{
				return this._IloscSztZm;
			}
			set
			{
				if ((this._IloscSztZm != value))
				{
					this._IloscSztZm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataWprowadzenia", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataWprowadzenia
		{
			get
			{
				return this._DataWprowadzenia;
			}
			set
			{
				if ((this._DataWprowadzenia != value))
				{
					this._DataWprowadzenia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObowiązujeOd", DbType="DateTime")]
		public System.Nullable<System.DateTime> ObowiązujeOd
		{
			get
			{
				return this._ObowiązujeOd;
			}
			set
			{
				if ((this._ObowiązujeOd != value))
				{
					this._ObowiązujeOd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObowiązujeDo", DbType="DateTime")]
		public System.Nullable<System.DateTime> ObowiązujeDo
		{
			get
			{
				return this._ObowiązujeDo;
			}
			set
			{
				if ((this._ObowiązujeDo != value))
				{
					this._ObowiązujeDo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marszruty_szlifiernia_")]
	public partial class Marszruty_szlif
	{
		
		private string _Id_wyrobu;
		
		private string _Nazwa_wyrobu;
		
		private string _Kolor;
		
		private string _Nazwa_operacji;
		
		private string _KodOperacjiPS;
		
		private int _Id_operacji;
		
		private System.Nullable<int> _IloscSztZm;
		
		private string _NormaZatwierdzona;
		
		public Marszruty_szlif()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_wyrobu", DbType="NVarChar(255)")]
		public string Id_wyrobu
		{
			get
			{
				return this._Id_wyrobu;
			}
			set
			{
				if ((this._Id_wyrobu != value))
				{
					this._Id_wyrobu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_wyrobu", DbType="NVarChar(50)")]
		public string Nazwa_wyrobu
		{
			get
			{
				return this._Nazwa_wyrobu;
			}
			set
			{
				if ((this._Nazwa_wyrobu != value))
				{
					this._Nazwa_wyrobu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kolor", DbType="NVarChar(50)")]
		public string Kolor
		{
			get
			{
				return this._Kolor;
			}
			set
			{
				if ((this._Kolor != value))
				{
					this._Kolor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nazwa operacji]", Storage="_Nazwa_operacji", DbType="NVarChar(50)")]
		public string Nazwa_operacji
		{
			get
			{
				return this._Nazwa_operacji;
			}
			set
			{
				if ((this._Nazwa_operacji != value))
				{
					this._Nazwa_operacji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodOperacjiPS", DbType="NChar(5)")]
		public string KodOperacjiPS
		{
			get
			{
				return this._KodOperacjiPS;
			}
			set
			{
				if ((this._KodOperacjiPS != value))
				{
					this._KodOperacjiPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_operacji", DbType="Int NOT NULL")]
		public int Id_operacji
		{
			get
			{
				return this._Id_operacji;
			}
			set
			{
				if ((this._Id_operacji != value))
				{
					this._Id_operacji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IloscSztZm", DbType="Int")]
		public System.Nullable<int> IloscSztZm
		{
			get
			{
				return this._IloscSztZm;
			}
			set
			{
				if ((this._IloscSztZm != value))
				{
					this._IloscSztZm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NormaZatwierdzona", DbType="NChar(3) NOT NULL", CanBeNull=false)]
		public string NormaZatwierdzona
		{
			get
			{
				return this._NormaZatwierdzona;
			}
			set
			{
				if ((this._NormaZatwierdzona != value))
				{
					this._NormaZatwierdzona = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Szlifiernia_operacje_skan")]
	public partial class Szlifiernia_operacje_skan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nr_zlecenia_nr_partii;
		
		private string _Nr_zlecenia;
		
		private string _Kod_detalu;
		
		private string _Nazwa_operacji;
		
		private string _ID_Operacji;
		
		private string _ID_Usera;
		
		private string _Nazwa_usera;
		
		private System.Nullable<int> _Ilosc_ok;
		
		private System.Nullable<int> _Ilosc_izolator;
		
		private System.Nullable<System.DateTime> _Czas_stop;
		
		private string _Do_poprawy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNr_zlecenia_nr_partiiChanging(string value);
    partial void OnNr_zlecenia_nr_partiiChanged();
    partial void OnNr_zleceniaChanging(string value);
    partial void OnNr_zleceniaChanged();
    partial void OnKod_detaluChanging(string value);
    partial void OnKod_detaluChanged();
    partial void OnNazwa_operacjiChanging(string value);
    partial void OnNazwa_operacjiChanged();
    partial void OnID_OperacjiChanging(string value);
    partial void OnID_OperacjiChanged();
    partial void OnID_UseraChanging(string value);
    partial void OnID_UseraChanged();
    partial void OnNazwa_useraChanging(string value);
    partial void OnNazwa_useraChanged();
    partial void OnIlosc_okChanging(System.Nullable<int> value);
    partial void OnIlosc_okChanged();
    partial void OnIlosc_izolatorChanging(System.Nullable<int> value);
    partial void OnIlosc_izolatorChanged();
    partial void OnCzas_stopChanging(System.Nullable<System.DateTime> value);
    partial void OnCzas_stopChanged();
    partial void OnDo_poprawyChanging(string value);
    partial void OnDo_poprawyChanged();
    #endregion
		
		public Szlifiernia_operacje_skan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_zlecenia_nr_partii", DbType="NVarChar(50)")]
		public string Nr_zlecenia_nr_partii
		{
			get
			{
				return this._Nr_zlecenia_nr_partii;
			}
			set
			{
				if ((this._Nr_zlecenia_nr_partii != value))
				{
					this.OnNr_zlecenia_nr_partiiChanging(value);
					this.SendPropertyChanging();
					this._Nr_zlecenia_nr_partii = value;
					this.SendPropertyChanged("Nr_zlecenia_nr_partii");
					this.OnNr_zlecenia_nr_partiiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_zlecenia", DbType="NVarChar(50)")]
		public string Nr_zlecenia
		{
			get
			{
				return this._Nr_zlecenia;
			}
			set
			{
				if ((this._Nr_zlecenia != value))
				{
					this.OnNr_zleceniaChanging(value);
					this.SendPropertyChanging();
					this._Nr_zlecenia = value;
					this.SendPropertyChanged("Nr_zlecenia");
					this.OnNr_zleceniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_detalu", DbType="NVarChar(50)")]
		public string Kod_detalu
		{
			get
			{
				return this._Kod_detalu;
			}
			set
			{
				if ((this._Kod_detalu != value))
				{
					this.OnKod_detaluChanging(value);
					this.SendPropertyChanging();
					this._Kod_detalu = value;
					this.SendPropertyChanged("Kod_detalu");
					this.OnKod_detaluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_operacji", DbType="NVarChar(150)")]
		public string Nazwa_operacji
		{
			get
			{
				return this._Nazwa_operacji;
			}
			set
			{
				if ((this._Nazwa_operacji != value))
				{
					this.OnNazwa_operacjiChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_operacji = value;
					this.SendPropertyChanged("Nazwa_operacji");
					this.OnNazwa_operacjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Operacji", DbType="NVarChar(50)")]
		public string ID_Operacji
		{
			get
			{
				return this._ID_Operacji;
			}
			set
			{
				if ((this._ID_Operacji != value))
				{
					this.OnID_OperacjiChanging(value);
					this.SendPropertyChanging();
					this._ID_Operacji = value;
					this.SendPropertyChanged("ID_Operacji");
					this.OnID_OperacjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usera", DbType="NVarChar(50)")]
		public string ID_Usera
		{
			get
			{
				return this._ID_Usera;
			}
			set
			{
				if ((this._ID_Usera != value))
				{
					this.OnID_UseraChanging(value);
					this.SendPropertyChanging();
					this._ID_Usera = value;
					this.SendPropertyChanged("ID_Usera");
					this.OnID_UseraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_usera", DbType="NVarChar(150)")]
		public string Nazwa_usera
		{
			get
			{
				return this._Nazwa_usera;
			}
			set
			{
				if ((this._Nazwa_usera != value))
				{
					this.OnNazwa_useraChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_usera = value;
					this.SendPropertyChanged("Nazwa_usera");
					this.OnNazwa_useraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_ok", DbType="Int")]
		public System.Nullable<int> Ilosc_ok
		{
			get
			{
				return this._Ilosc_ok;
			}
			set
			{
				if ((this._Ilosc_ok != value))
				{
					this.OnIlosc_okChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_ok = value;
					this.SendPropertyChanged("Ilosc_ok");
					this.OnIlosc_okChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_izolator", DbType="Int")]
		public System.Nullable<int> Ilosc_izolator
		{
			get
			{
				return this._Ilosc_izolator;
			}
			set
			{
				if ((this._Ilosc_izolator != value))
				{
					this.OnIlosc_izolatorChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_izolator = value;
					this.SendPropertyChanged("Ilosc_izolator");
					this.OnIlosc_izolatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Czas_stop", DbType="DateTime")]
		public System.Nullable<System.DateTime> Czas_stop
		{
			get
			{
				return this._Czas_stop;
			}
			set
			{
				if ((this._Czas_stop != value))
				{
					this.OnCzas_stopChanging(value);
					this.SendPropertyChanging();
					this._Czas_stop = value;
					this.SendPropertyChanged("Czas_stop");
					this.OnCzas_stopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Do_poprawy", DbType="NVarChar(50)")]
		public string Do_poprawy
		{
			get
			{
				return this._Do_poprawy;
			}
			set
			{
				if ((this._Do_poprawy != value))
				{
					this.OnDo_poprawyChanging(value);
					this.SendPropertyChanging();
					this._Do_poprawy = value;
					this.SendPropertyChanged("Do_poprawy");
					this.OnDo_poprawyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wykonanie_szlifiernia_norma")]
	public partial class Wykonanie_szlifiernia_normas
	{
		
		private int _ID;
		
		private string _Nr_zlecenia_nr_partii;
		
		private string _Nr_zlecenia;
		
		private string _Kod_detalu;
		
		private string _ID_Operacji;
		
		private string _ID_Usera;
		
		private string _Nazwa_operacji;
		
		private string _Nazwisko_prac;
		
		private System.Nullable<int> _Ilosc_izolator;
		
		private System.Nullable<System.DateTime> _Czas_start;
		
		private System.Nullable<System.DateTime> _Czas_stop;
		
		private System.Nullable<decimal> _czas_operacji_min;
		
		private int _IlośćSztukZm;
		
		private System.Nullable<decimal> _Minuty_wg_normy;
		
		private System.Nullable<decimal> _ilosc_wg_normy;
		
		private System.Nullable<int> _Ilosc_ok;
		
		private System.Nullable<System.DateTime> _DATA_;
		
		private string _Nazwa_detalu;
		
		public Wykonanie_szlifiernia_normas()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_zlecenia_nr_partii", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nr_zlecenia_nr_partii
		{
			get
			{
				return this._Nr_zlecenia_nr_partii;
			}
			set
			{
				if ((this._Nr_zlecenia_nr_partii != value))
				{
					this._Nr_zlecenia_nr_partii = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_zlecenia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nr_zlecenia
		{
			get
			{
				return this._Nr_zlecenia;
			}
			set
			{
				if ((this._Nr_zlecenia != value))
				{
					this._Nr_zlecenia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_detalu", DbType="NVarChar(50)")]
		public string Kod_detalu
		{
			get
			{
				return this._Kod_detalu;
			}
			set
			{
				if ((this._Kod_detalu != value))
				{
					this._Kod_detalu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Operacji", DbType="NVarChar(50)")]
		public string ID_Operacji
		{
			get
			{
				return this._ID_Operacji;
			}
			set
			{
				if ((this._ID_Operacji != value))
				{
					this._ID_Operacji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usera", DbType="NVarChar(50)")]
		public string ID_Usera
		{
			get
			{
				return this._ID_Usera;
			}
			set
			{
				if ((this._ID_Usera != value))
				{
					this._ID_Usera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_operacji", DbType="NVarChar(50)")]
		public string Nazwa_operacji
		{
			get
			{
				return this._Nazwa_operacji;
			}
			set
			{
				if ((this._Nazwa_operacji != value))
				{
					this._Nazwa_operacji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko_prac", DbType="NVarChar(50)")]
		public string Nazwisko_prac
		{
			get
			{
				return this._Nazwisko_prac;
			}
			set
			{
				if ((this._Nazwisko_prac != value))
				{
					this._Nazwisko_prac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_izolator", DbType="Int")]
		public System.Nullable<int> Ilosc_izolator
		{
			get
			{
				return this._Ilosc_izolator;
			}
			set
			{
				if ((this._Ilosc_izolator != value))
				{
					this._Ilosc_izolator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Czas_start", DbType="DateTime")]
		public System.Nullable<System.DateTime> Czas_start
		{
			get
			{
				return this._Czas_start;
			}
			set
			{
				if ((this._Czas_start != value))
				{
					this._Czas_start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Czas_stop", DbType="DateTime")]
		public System.Nullable<System.DateTime> Czas_stop
		{
			get
			{
				return this._Czas_stop;
			}
			set
			{
				if ((this._Czas_stop != value))
				{
					this._Czas_stop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_czas_operacji_min", DbType="Decimal(24,6)")]
		public System.Nullable<decimal> czas_operacji_min
		{
			get
			{
				return this._czas_operacji_min;
			}
			set
			{
				if ((this._czas_operacji_min != value))
				{
					this._czas_operacji_min = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IlośćSztukZm", DbType="Int NOT NULL")]
		public int IlośćSztukZm
		{
			get
			{
				return this._IlośćSztukZm;
			}
			set
			{
				if ((this._IlośćSztukZm != value))
				{
					this._IlośćSztukZm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Minuty_wg_normy", DbType="Decimal(38,10)")]
		public System.Nullable<decimal> Minuty_wg_normy
		{
			get
			{
				return this._Minuty_wg_normy;
			}
			set
			{
				if ((this._Minuty_wg_normy != value))
				{
					this._Minuty_wg_normy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilosc_wg_normy", DbType="Decimal(38,9)")]
		public System.Nullable<decimal> ilosc_wg_normy
		{
			get
			{
				return this._ilosc_wg_normy;
			}
			set
			{
				if ((this._ilosc_wg_normy != value))
				{
					this._ilosc_wg_normy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_ok", DbType="Int")]
		public System.Nullable<int> Ilosc_ok
		{
			get
			{
				return this._Ilosc_ok;
			}
			set
			{
				if ((this._Ilosc_ok != value))
				{
					this._Ilosc_ok = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_
		{
			get
			{
				return this._DATA_;
			}
			set
			{
				if ((this._DATA_ != value))
				{
					this._DATA_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_detalu", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Nazwa_detalu
		{
			get
			{
				return this._Nazwa_detalu;
			}
			set
			{
				if ((this._Nazwa_detalu != value))
				{
					this._Nazwa_detalu = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
