#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_SharePoint
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KARTY_PRODUKCJI")]
	public partial class DBKartyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGAL_BAZA_ZAWIESZEK(GAL_BAZA_ZAWIESZEK instance);
    partial void UpdateGAL_BAZA_ZAWIESZEK(GAL_BAZA_ZAWIESZEK instance);
    partial void DeleteGAL_BAZA_ZAWIESZEK(GAL_BAZA_ZAWIESZEK instance);
    partial void InsertGAL_wej_transakcje(GAL_wej_transakcje instance);
    partial void UpdateGAL_wej_transakcje(GAL_wej_transakcje instance);
    partial void DeleteGAL_wej_transakcje(GAL_wej_transakcje instance);
    partial void InsertGAL_Stany(GAL_Stany instance);
    partial void UpdateGAL_Stany(GAL_Stany instance);
    partial void DeleteGAL_Stany(GAL_Stany instance);
    #endregion
		
		public DBKartyDataContext() : 
				base(global::WebService_SharePoint.Properties.Settings.Default.KARTY_PRODUKCJIConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DBKartyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBKartyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBKartyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBKartyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GAL_BAZA_ZAWIESZEK> GAL_BAZA_ZAWIESZEK
		{
			get
			{
				return this.GetTable<GAL_BAZA_ZAWIESZEK>();
			}
		}
		
		public System.Data.Linq.Table<GAL_wej_transakcje> GAL_wej_transakcje
		{
			get
			{
				return this.GetTable<GAL_wej_transakcje>();
			}
		}
		
		public System.Data.Linq.Table<GAL_Stany> GAL_Stany
		{
			get
			{
				return this.GetTable<GAL_Stany>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GAL_BAZA_ZAWIESZEK")]
	public partial class GAL_BAZA_ZAWIESZEK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nr_zawieszki;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _CreatedBy;
		
		private string _GALMAL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNr_zawieszkiChanging(string value);
    partial void OnNr_zawieszkiChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnGALMALChanging(string value);
    partial void OnGALMALChanged();
    #endregion
		
		public GAL_BAZA_ZAWIESZEK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_zawieszki", DbType="NVarChar(50)")]
		public string Nr_zawieszki
		{
			get
			{
				return this._Nr_zawieszki;
			}
			set
			{
				if ((this._Nr_zawieszki != value))
				{
					this.OnNr_zawieszkiChanging(value);
					this.SendPropertyChanging();
					this._Nr_zawieszki = value;
					this.SendPropertyChanged("Nr_zawieszki");
					this.OnNr_zawieszkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GALMAL", DbType="NVarChar(50)")]
		public string GALMAL
		{
			get
			{
				return this._GALMAL;
			}
			set
			{
				if ((this._GALMAL != value))
				{
					this.OnGALMALChanging(value);
					this.SendPropertyChanging();
					this._GALMAL = value;
					this.SendPropertyChanged("GALMAL");
					this.OnGALMALChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GAL_wej_transakcje")]
	public partial class GAL_wej_transakcje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _indeks;
		
		private int _ilosc_szt;
		
		private System.DateTime _data_przyj;
		
		private string _user;
		
		private string _komentarz;
		
		private string _skan;
		
		private string _lok;
		
		private System.Nullable<System.DateTime> _data_zamkniecia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnindeksChanging(string value);
    partial void OnindeksChanged();
    partial void Onilosc_sztChanging(int value);
    partial void Onilosc_sztChanged();
    partial void Ondata_przyjChanging(System.DateTime value);
    partial void Ondata_przyjChanged();
    partial void OnuserChanging(string value);
    partial void OnuserChanged();
    partial void OnkomentarzChanging(string value);
    partial void OnkomentarzChanged();
    partial void OnskanChanging(string value);
    partial void OnskanChanged();
    partial void OnlokChanging(string value);
    partial void OnlokChanged();
    partial void Ondata_zamknieciaChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_zamknieciaChanged();
    #endregion
		
		public GAL_wej_transakcje()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indeks", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string indeks
		{
			get
			{
				return this._indeks;
			}
			set
			{
				if ((this._indeks != value))
				{
					this.OnindeksChanging(value);
					this.SendPropertyChanging();
					this._indeks = value;
					this.SendPropertyChanged("indeks");
					this.OnindeksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilosc_szt", DbType="Int NOT NULL")]
		public int ilosc_szt
		{
			get
			{
				return this._ilosc_szt;
			}
			set
			{
				if ((this._ilosc_szt != value))
				{
					this.Onilosc_sztChanging(value);
					this.SendPropertyChanging();
					this._ilosc_szt = value;
					this.SendPropertyChanged("ilosc_szt");
					this.Onilosc_sztChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_przyj", DbType="DateTime NOT NULL")]
		public System.DateTime data_przyj
		{
			get
			{
				return this._data_przyj;
			}
			set
			{
				if ((this._data_przyj != value))
				{
					this.Ondata_przyjChanging(value);
					this.SendPropertyChanging();
					this._data_przyj = value;
					this.SendPropertyChanged("data_przyj");
					this.Ondata_przyjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[user]", Storage="_user", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user
		{
			get
			{
				return this._user;
			}
			set
			{
				if ((this._user != value))
				{
					this.OnuserChanging(value);
					this.SendPropertyChanging();
					this._user = value;
					this.SendPropertyChanged("user");
					this.OnuserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_komentarz", DbType="NVarChar(50)")]
		public string komentarz
		{
			get
			{
				return this._komentarz;
			}
			set
			{
				if ((this._komentarz != value))
				{
					this.OnkomentarzChanging(value);
					this.SendPropertyChanging();
					this._komentarz = value;
					this.SendPropertyChanged("komentarz");
					this.OnkomentarzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string skan
		{
			get
			{
				return this._skan;
			}
			set
			{
				if ((this._skan != value))
				{
					this.OnskanChanging(value);
					this.SendPropertyChanging();
					this._skan = value;
					this.SendPropertyChanged("skan");
					this.OnskanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lok", DbType="NVarChar(50)")]
		public string lok
		{
			get
			{
				return this._lok;
			}
			set
			{
				if ((this._lok != value))
				{
					this.OnlokChanging(value);
					this.SendPropertyChanging();
					this._lok = value;
					this.SendPropertyChanged("lok");
					this.OnlokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_zamkniecia", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_zamkniecia
		{
			get
			{
				return this._data_zamkniecia;
			}
			set
			{
				if ((this._data_zamkniecia != value))
				{
					this.Ondata_zamknieciaChanging(value);
					this.SendPropertyChanging();
					this._data_zamkniecia = value;
					this.SendPropertyChanged("data_zamkniecia");
					this.Ondata_zamknieciaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GAL_Stany")]
	public partial class GAL_Stany : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _indeks;
		
		private string _lok;
		
		private System.Nullable<int> _ilość;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnindeksChanging(string value);
    partial void OnindeksChanged();
    partial void OnlokChanging(string value);
    partial void OnlokChanged();
    partial void OnilośćChanging(System.Nullable<int> value);
    partial void OnilośćChanged();
    #endregion
		
		public GAL_Stany()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indeks", DbType="NVarChar(50)")]
		public string indeks
		{
			get
			{
				return this._indeks;
			}
			set
			{
				if ((this._indeks != value))
				{
					this.OnindeksChanging(value);
					this.SendPropertyChanging();
					this._indeks = value;
					this.SendPropertyChanged("indeks");
					this.OnindeksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lok", DbType="NVarChar(50)")]
		public string lok
		{
			get
			{
				return this._lok;
			}
			set
			{
				if ((this._lok != value))
				{
					this.OnlokChanging(value);
					this.SendPropertyChanging();
					this._lok = value;
					this.SendPropertyChanged("lok");
					this.OnlokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilość", DbType="Int")]
		public System.Nullable<int> ilość
		{
			get
			{
				return this._ilość;
			}
			set
			{
				if ((this._ilość != value))
				{
					this.OnilośćChanging(value);
					this.SendPropertyChanging();
					this._ilość = value;
					this.SendPropertyChanged("ilość");
					this.OnilośćChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
