#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_SharePoint
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KARTY_PRODUKCJI")]
	public partial class dbKartyProdukcjiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKJ_szlifiernia_potwierdzone(KJ_szlifiernia_potwierdzone instance);
    partial void UpdateKJ_szlifiernia_potwierdzone(KJ_szlifiernia_potwierdzone instance);
    partial void DeleteKJ_szlifiernia_potwierdzone(KJ_szlifiernia_potwierdzone instance);
    partial void InsertGAL_powody_brakow(GAL_powody_brakow instance);
    partial void UpdateGAL_powody_brakow(GAL_powody_brakow instance);
    partial void DeleteGAL_powody_brakow(GAL_powody_brakow instance);
    partial void InsertGAL_ZDJECIA(GAL_ZDJECIA instance);
    partial void UpdateGAL_ZDJECIA(GAL_ZDJECIA instance);
    partial void DeleteGAL_ZDJECIA(GAL_ZDJECIA instance);
    #endregion
		
		public dbKartyProdukcjiDataContext() : 
				base(global::WebService_SharePoint.Properties.Settings.Default.KARTY_PRODUKCJIConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public dbKartyProdukcjiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbKartyProdukcjiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbKartyProdukcjiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbKartyProdukcjiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KJ_szlifiernia_potwierdzone> KJ_szlifiernia_potwierdzones
		{
			get
			{
				return this.GetTable<KJ_szlifiernia_potwierdzone>();
			}
		}
		
		public System.Data.Linq.Table<GAL_powody_brakow> GAL_powody_brakow
		{
			get
			{
				return this.GetTable<GAL_powody_brakow>();
			}
		}
		
		public System.Data.Linq.Table<GAL_ZAWIESZKI> GAL_ZAWIESZKIs
		{
			get
			{
				return this.GetTable<GAL_ZAWIESZKI>();
			}
		}
		
		public System.Data.Linq.Table<GAL_ZDJECIA> GAL_ZDJECIAs
		{
			get
			{
				return this.GetTable<GAL_ZDJECIA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KJ_szlifiernia_potwierdzone")]
	public partial class KJ_szlifiernia_potwierdzone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Kod_detalu;
		
		private string _Nazwa_detalu;
		
		private System.Nullable<int> _Ilosc_ok;
		
		private System.Nullable<System.DateTime> _Data_powierdzenia;
		
		private string _ID_usera;
		
		private string _Nagl_skan;
		
		private string _STATUS;
		
		private string _Przesuniecie;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKod_detaluChanging(string value);
    partial void OnKod_detaluChanged();
    partial void OnNazwa_detaluChanging(string value);
    partial void OnNazwa_detaluChanged();
    partial void OnIlosc_okChanging(System.Nullable<int> value);
    partial void OnIlosc_okChanged();
    partial void OnData_powierdzeniaChanging(System.Nullable<System.DateTime> value);
    partial void OnData_powierdzeniaChanged();
    partial void OnID_useraChanging(string value);
    partial void OnID_useraChanged();
    partial void OnNagl_skanChanging(string value);
    partial void OnNagl_skanChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnPrzesuniecieChanging(string value);
    partial void OnPrzesuniecieChanged();
    #endregion
		
		public KJ_szlifiernia_potwierdzone()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_detalu", DbType="NVarChar(50)")]
		public string Kod_detalu
		{
			get
			{
				return this._Kod_detalu;
			}
			set
			{
				if ((this._Kod_detalu != value))
				{
					this.OnKod_detaluChanging(value);
					this.SendPropertyChanging();
					this._Kod_detalu = value;
					this.SendPropertyChanged("Kod_detalu");
					this.OnKod_detaluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_detalu", DbType="NVarChar(150)")]
		public string Nazwa_detalu
		{
			get
			{
				return this._Nazwa_detalu;
			}
			set
			{
				if ((this._Nazwa_detalu != value))
				{
					this.OnNazwa_detaluChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_detalu = value;
					this.SendPropertyChanged("Nazwa_detalu");
					this.OnNazwa_detaluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_ok", DbType="Int")]
		public System.Nullable<int> Ilosc_ok
		{
			get
			{
				return this._Ilosc_ok;
			}
			set
			{
				if ((this._Ilosc_ok != value))
				{
					this.OnIlosc_okChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_ok = value;
					this.SendPropertyChanged("Ilosc_ok");
					this.OnIlosc_okChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_powierdzenia", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data_powierdzenia
		{
			get
			{
				return this._Data_powierdzenia;
			}
			set
			{
				if ((this._Data_powierdzenia != value))
				{
					this.OnData_powierdzeniaChanging(value);
					this.SendPropertyChanging();
					this._Data_powierdzenia = value;
					this.SendPropertyChanged("Data_powierdzenia");
					this.OnData_powierdzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_usera", DbType="NVarChar(50)")]
		public string ID_usera
		{
			get
			{
				return this._ID_usera;
			}
			set
			{
				if ((this._ID_usera != value))
				{
					this.OnID_useraChanging(value);
					this.SendPropertyChanging();
					this._ID_usera = value;
					this.SendPropertyChanged("ID_usera");
					this.OnID_useraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nagl_skan", DbType="NVarChar(50)")]
		public string Nagl_skan
		{
			get
			{
				return this._Nagl_skan;
			}
			set
			{
				if ((this._Nagl_skan != value))
				{
					this.OnNagl_skanChanging(value);
					this.SendPropertyChanging();
					this._Nagl_skan = value;
					this.SendPropertyChanged("Nagl_skan");
					this.OnNagl_skanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="NVarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Przesuniecie", DbType="NVarChar(50)")]
		public string Przesuniecie
		{
			get
			{
				return this._Przesuniecie;
			}
			set
			{
				if ((this._Przesuniecie != value))
				{
					this.OnPrzesuniecieChanging(value);
					this.SendPropertyChanging();
					this._Przesuniecie = value;
					this.SendPropertyChanged("Przesuniecie");
					this.OnPrzesuniecieChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GAL_powody_brakow")]
	public partial class GAL_powody_brakow : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Kod_Braku;
		
		private string _Opis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKod_BrakuChanging(string value);
    partial void OnKod_BrakuChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    #endregion
		
		public GAL_powody_brakow()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_Braku", DbType="NVarChar(50)")]
		public string Kod_Braku
		{
			get
			{
				return this._Kod_Braku;
			}
			set
			{
				if ((this._Kod_Braku != value))
				{
					this.OnKod_BrakuChanging(value);
					this.SendPropertyChanging();
					this._Kod_Braku = value;
					this.SendPropertyChanged("Kod_Braku");
					this.OnKod_BrakuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(50)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GAL_ZAWIESZKI")]
	public partial class GAL_ZAWIESZKI
	{
		
		private int _ID;
		
		private string _Nr_rysunku;
		
		private string _Nr_zawieszki;
		
		private string _Program;
		
		private System.Nullable<int> _Il_szt;
		
		private string _Komentarz;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _CreatedBy;
		
		private System.Nullable<int> _Ilosc_zdjęć;
		
		private string _GALMAL;
		
		public GAL_ZAWIESZKI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_rysunku", DbType="NVarChar(90)")]
		public string Nr_rysunku
		{
			get
			{
				return this._Nr_rysunku;
			}
			set
			{
				if ((this._Nr_rysunku != value))
				{
					this._Nr_rysunku = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_zawieszki", DbType="NVarChar(50)")]
		public string Nr_zawieszki
		{
			get
			{
				return this._Nr_zawieszki;
			}
			set
			{
				if ((this._Nr_zawieszki != value))
				{
					this._Nr_zawieszki = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Program", DbType="NVarChar(50)")]
		public string Program
		{
			get
			{
				return this._Program;
			}
			set
			{
				if ((this._Program != value))
				{
					this._Program = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Il_szt", DbType="Int")]
		public System.Nullable<int> Il_szt
		{
			get
			{
				return this._Il_szt;
			}
			set
			{
				if ((this._Il_szt != value))
				{
					this._Il_szt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Komentarz", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Komentarz
		{
			get
			{
				return this._Komentarz;
			}
			set
			{
				if ((this._Komentarz != value))
				{
					this._Komentarz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this._Created = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this._CreatedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc_zdjęć", DbType="Int")]
		public System.Nullable<int> Ilosc_zdjęć
		{
			get
			{
				return this._Ilosc_zdjęć;
			}
			set
			{
				if ((this._Ilosc_zdjęć != value))
				{
					this._Ilosc_zdjęć = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GALMAL", DbType="NVarChar(50)")]
		public string GALMAL
		{
			get
			{
				return this._GALMAL;
			}
			set
			{
				if ((this._GALMAL != value))
				{
					this._GALMAL = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GAL_ZDJECIA")]
	public partial class GAL_ZDJECIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_zawieszki;
		
		private System.Data.Linq.Binary _Zdjecie;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _CreatedBy;
		
		private string _Komentarz;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_zawieszkiChanging(System.Nullable<int> value);
    partial void OnID_zawieszkiChanged();
    partial void OnZdjecieChanging(System.Data.Linq.Binary value);
    partial void OnZdjecieChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnKomentarzChanging(string value);
    partial void OnKomentarzChanged();
    #endregion
		
		public GAL_ZDJECIA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_zawieszki", DbType="Int")]
		public System.Nullable<int> ID_zawieszki
		{
			get
			{
				return this._ID_zawieszki;
			}
			set
			{
				if ((this._ID_zawieszki != value))
				{
					this.OnID_zawieszkiChanging(value);
					this.SendPropertyChanging();
					this._ID_zawieszki = value;
					this.SendPropertyChanged("ID_zawieszki");
					this.OnID_zawieszkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zdjecie", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Zdjecie
		{
			get
			{
				return this._Zdjecie;
			}
			set
			{
				if ((this._Zdjecie != value))
				{
					this.OnZdjecieChanging(value);
					this.SendPropertyChanging();
					this._Zdjecie = value;
					this.SendPropertyChanged("Zdjecie");
					this.OnZdjecieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Komentarz", DbType="NVarChar(250)")]
		public string Komentarz
		{
			get
			{
				return this._Komentarz;
			}
			set
			{
				if ((this._Komentarz != value))
				{
					this.OnKomentarzChanging(value);
					this.SendPropertyChanging();
					this._Komentarz = value;
					this.SendPropertyChanged("Komentarz");
					this.OnKomentarzChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
