#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_SharePoint
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Planowanie szlifiernia_wb")]
	public partial class DBSZlifDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPracownicy(Pracownicy instance);
    partial void UpdatePracownicy(Pracownicy instance);
    partial void DeletePracownicy(Pracownicy instance);
    #endregion
		
		public DBSZlifDataContext() : 
				base(global::WebService_SharePoint.Properties.Settings.Default.Planowanie_szlifiernia_wbConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DBSZlifDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSZlifDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSZlifDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBSZlifDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Pracownicy> Pracownicy
		{
			get
			{
				return this.GetTable<Pracownicy>();
			}
		}
		
		public System.Data.Linq.Table<Operacje_PS> Operacje_PS
		{
			get
			{
				return this.GetTable<Operacje_PS>();
			}
		}
		
		public System.Data.Linq.Table<Zdawka> Zdawkas
		{
			get
			{
				return this.GetTable<Zdawka>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pracownicy")]
	public partial class Pracownicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Pracownika;
		
		private string _Nazwisko_prac;
		
		private string _Stanowisko;
		
		private string _Id_Centrum;
		
		private string _Id_Zmiany;
		
		private string _Grupa;
		
		private System.Nullable<int> @__1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_PracownikaChanging(int value);
    partial void OnId_PracownikaChanged();
    partial void OnNazwisko_pracChanging(string value);
    partial void OnNazwisko_pracChanged();
    partial void OnStanowiskoChanging(string value);
    partial void OnStanowiskoChanged();
    partial void OnId_CentrumChanging(string value);
    partial void OnId_CentrumChanged();
    partial void OnId_ZmianyChanging(string value);
    partial void OnId_ZmianyChanged();
    partial void OnGrupaChanging(string value);
    partial void OnGrupaChanged();
    partial void On_1Changing(System.Nullable<int> value);
    partial void On_1Changed();
    #endregion
		
		public Pracownicy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Pracownika", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Pracownika
		{
			get
			{
				return this._Id_Pracownika;
			}
			set
			{
				if ((this._Id_Pracownika != value))
				{
					this.OnId_PracownikaChanging(value);
					this.SendPropertyChanging();
					this._Id_Pracownika = value;
					this.SendPropertyChanged("Id_Pracownika");
					this.OnId_PracownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko_prac", DbType="NVarChar(50)")]
		public string Nazwisko_prac
		{
			get
			{
				return this._Nazwisko_prac;
			}
			set
			{
				if ((this._Nazwisko_prac != value))
				{
					this.OnNazwisko_pracChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko_prac = value;
					this.SendPropertyChanged("Nazwisko_prac");
					this.OnNazwisko_pracChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stanowisko", DbType="NVarChar(50)")]
		public string Stanowisko
		{
			get
			{
				return this._Stanowisko;
			}
			set
			{
				if ((this._Stanowisko != value))
				{
					this.OnStanowiskoChanging(value);
					this.SendPropertyChanging();
					this._Stanowisko = value;
					this.SendPropertyChanged("Stanowisko");
					this.OnStanowiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Centrum", DbType="NVarChar(8)")]
		public string Id_Centrum
		{
			get
			{
				return this._Id_Centrum;
			}
			set
			{
				if ((this._Id_Centrum != value))
				{
					this.OnId_CentrumChanging(value);
					this.SendPropertyChanging();
					this._Id_Centrum = value;
					this.SendPropertyChanged("Id_Centrum");
					this.OnId_CentrumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Zmiany", DbType="NVarChar(2)")]
		public string Id_Zmiany
		{
			get
			{
				return this._Id_Zmiany;
			}
			set
			{
				if ((this._Id_Zmiany != value))
				{
					this.OnId_ZmianyChanging(value);
					this.SendPropertyChanging();
					this._Id_Zmiany = value;
					this.SendPropertyChanged("Id_Zmiany");
					this.OnId_ZmianyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grupa", DbType="NVarChar(50)")]
		public string Grupa
		{
			get
			{
				return this._Grupa;
			}
			set
			{
				if ((this._Grupa != value))
				{
					this.OnGrupaChanging(value);
					this.SendPropertyChanging();
					this._Grupa = value;
					this.SendPropertyChanged("Grupa");
					this.OnGrupaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1]", Storage="__1", DbType="Int")]
		public System.Nullable<int> _1
		{
			get
			{
				return this.@__1;
			}
			set
			{
				if ((this.@__1 != value))
				{
					this.On_1Changing(value);
					this.SendPropertyChanging();
					this.@__1 = value;
					this.SendPropertyChanged("_1");
					this.On_1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Operacje PS]")]
	public partial class Operacje_PS
	{
		
		private string _KodCzęści;
		
		private string _NazwaCzęści;
		
		private string _kod2;
		
		private double _NrkolOperacji;
		
		private System.Nullable<double> _NormaCzasowa;
		
		private System.Nullable<int> _IlośćSztukZm;
		
		private System.Nullable<System.DateTime> _ObowiązujeOd1;
		
		private System.Nullable<System.DateTime> _ObowiązujeDO1;
		
		private string _KodOperacjiPS;
		
		private string _NazwaOperacji;
		
		private int _Id_operacji;
		
		private string _CentrumRobocze;
		
		private decimal _ObowiązujeOd;
		
		private System.Nullable<decimal> _ObowiązujeDo;
		
		private string _IRTRT;
		
		private string _Wykończenie;
		
		private System.Nullable<double> _IlośćSztukZm1;
		
		private string _NrKartyTechn;
		
		public Operacje_PS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodCzęści", DbType="NVarChar(25)")]
		public string KodCzęści
		{
			get
			{
				return this._KodCzęści;
			}
			set
			{
				if ((this._KodCzęści != value))
				{
					this._KodCzęści = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazwaCzęści", DbType="NVarChar(30)")]
		public string NazwaCzęści
		{
			get
			{
				return this._NazwaCzęści;
			}
			set
			{
				if ((this._NazwaCzęści != value))
				{
					this._NazwaCzęści = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod2", DbType="NVarChar(36)")]
		public string kod2
		{
			get
			{
				return this._kod2;
			}
			set
			{
				if ((this._kod2 != value))
				{
					this._kod2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrkolOperacji", DbType="Float NOT NULL")]
		public double NrkolOperacji
		{
			get
			{
				return this._NrkolOperacji;
			}
			set
			{
				if ((this._NrkolOperacji != value))
				{
					this._NrkolOperacji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NormaCzasowa", DbType="Float")]
		public System.Nullable<double> NormaCzasowa
		{
			get
			{
				return this._NormaCzasowa;
			}
			set
			{
				if ((this._NormaCzasowa != value))
				{
					this._NormaCzasowa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IlośćSztukZm", DbType="Int")]
		public System.Nullable<int> IlośćSztukZm
		{
			get
			{
				return this._IlośćSztukZm;
			}
			set
			{
				if ((this._IlośćSztukZm != value))
				{
					this._IlośćSztukZm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObowiązujeOd1", DbType="DateTime")]
		public System.Nullable<System.DateTime> ObowiązujeOd1
		{
			get
			{
				return this._ObowiązujeOd1;
			}
			set
			{
				if ((this._ObowiązujeOd1 != value))
				{
					this._ObowiązujeOd1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObowiązujeDO1", DbType="DateTime")]
		public System.Nullable<System.DateTime> ObowiązujeDO1
		{
			get
			{
				return this._ObowiązujeDO1;
			}
			set
			{
				if ((this._ObowiązujeDO1 != value))
				{
					this._ObowiązujeDO1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodOperacjiPS", DbType="NChar(6)")]
		public string KodOperacjiPS
		{
			get
			{
				return this._KodOperacjiPS;
			}
			set
			{
				if ((this._KodOperacjiPS != value))
				{
					this._KodOperacjiPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazwaOperacji", DbType="NChar(30)")]
		public string NazwaOperacji
		{
			get
			{
				return this._NazwaOperacji;
			}
			set
			{
				if ((this._NazwaOperacji != value))
				{
					this._NazwaOperacji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_operacji", DbType="Int NOT NULL")]
		public int Id_operacji
		{
			get
			{
				return this._Id_operacji;
			}
			set
			{
				if ((this._Id_operacji != value))
				{
					this._Id_operacji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentrumRobocze", DbType="NVarChar(12)")]
		public string CentrumRobocze
		{
			get
			{
				return this._CentrumRobocze;
			}
			set
			{
				if ((this._CentrumRobocze != value))
				{
					this._CentrumRobocze = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObowiązujeOd", DbType="Decimal(18,0) NOT NULL")]
		public decimal ObowiązujeOd
		{
			get
			{
				return this._ObowiązujeOd;
			}
			set
			{
				if ((this._ObowiązujeOd != value))
				{
					this._ObowiązujeOd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObowiązujeDo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ObowiązujeDo
		{
			get
			{
				return this._ObowiązujeDo;
			}
			set
			{
				if ((this._ObowiązujeDo != value))
				{
					this._ObowiązujeDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IRTRT", DbType="NChar(3) NOT NULL", CanBeNull=false)]
		public string IRTRT
		{
			get
			{
				return this._IRTRT;
			}
			set
			{
				if ((this._IRTRT != value))
				{
					this._IRTRT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wykończenie", DbType="NVarChar(50)")]
		public string Wykończenie
		{
			get
			{
				return this._Wykończenie;
			}
			set
			{
				if ((this._Wykończenie != value))
				{
					this._Wykończenie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IlośćSztukZm1", DbType="Float")]
		public System.Nullable<double> IlośćSztukZm1
		{
			get
			{
				return this._IlośćSztukZm1;
			}
			set
			{
				if ((this._IlośćSztukZm1 != value))
				{
					this._IlośćSztukZm1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrKartyTechn", DbType="NChar(10)")]
		public string NrKartyTechn
		{
			get
			{
				return this._NrKartyTechn;
			}
			set
			{
				if ((this._NrKartyTechn != value))
				{
					this._NrKartyTechn = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zdawka")]
	public partial class Zdawka
	{
		
		private int _Id_przekaz;
		
		private string _Id_wyrobu;
		
		private System.Nullable<int> _Ilosc;
		
		private System.Nullable<System.DateTime> _Data_przekaz;
		
		private System.Data.Linq.Binary _s_ColLineage;
		
		private System.Nullable<int> _s_Generation;
		
		private System.Nullable<System.Guid> _s_GUID;
		
		private System.Data.Linq.Binary _s_Lineage;
		
		public Zdawka()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_przekaz", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id_przekaz
		{
			get
			{
				return this._Id_przekaz;
			}
			set
			{
				if ((this._Id_przekaz != value))
				{
					this._Id_przekaz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_wyrobu", DbType="NVarChar(50)")]
		public string Id_wyrobu
		{
			get
			{
				return this._Id_wyrobu;
			}
			set
			{
				if ((this._Id_wyrobu != value))
				{
					this._Id_wyrobu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc", DbType="Int")]
		public System.Nullable<int> Ilosc
		{
			get
			{
				return this._Ilosc;
			}
			set
			{
				if ((this._Ilosc != value))
				{
					this._Ilosc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data przekaz]", Storage="_Data_przekaz", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data_przekaz
		{
			get
			{
				return this._Data_przekaz;
			}
			set
			{
				if ((this._Data_przekaz != value))
				{
					this._Data_przekaz = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_ColLineage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary s_ColLineage
		{
			get
			{
				return this._s_ColLineage;
			}
			set
			{
				if ((this._s_ColLineage != value))
				{
					this._s_ColLineage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_Generation", DbType="Int")]
		public System.Nullable<int> s_Generation
		{
			get
			{
				return this._s_Generation;
			}
			set
			{
				if ((this._s_Generation != value))
				{
					this._s_Generation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_GUID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> s_GUID
		{
			get
			{
				return this._s_GUID;
			}
			set
			{
				if ((this._s_GUID != value))
				{
					this._s_GUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_Lineage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary s_Lineage
		{
			get
			{
				return this._s_Lineage;
			}
			set
			{
				if ((this._s_Lineage != value))
				{
					this._s_Lineage = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
