#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_SharePoint
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="trans")]
	public partial class dbtransDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGrupy(Grupy instance);
    partial void UpdateGrupy(Grupy instance);
    partial void DeleteGrupy(Grupy instance);
    partial void Insertgrupy_uzytkownicy(grupy_uzytkownicy instance);
    partial void Updategrupy_uzytkownicy(grupy_uzytkownicy instance);
    partial void Deletegrupy_uzytkownicy(grupy_uzytkownicy instance);
    partial void Insertuzytkownicy(uzytkownicy instance);
    partial void Updateuzytkownicy(uzytkownicy instance);
    partial void Deleteuzytkownicy(uzytkownicy instance);
    #endregion
		
		public dbtransDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["transConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbtransDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbtransDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbtransDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbtransDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Grupy> Grupy
		{
			get
			{
				return this.GetTable<Grupy>();
			}
		}
		
		public System.Data.Linq.Table<grupy_uzytkownicy> grupy_uzytkownicy
		{
			get
			{
				return this.GetTable<grupy_uzytkownicy>();
			}
		}
		
		public System.Data.Linq.Table<uzytkownicy> uzytkownicy
		{
			get
			{
				return this.GetTable<uzytkownicy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Grupy")]
	public partial class Grupy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Grupa;
		
		private string _Opis_grupy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnGrupaChanging(string value);
    partial void OnGrupaChanged();
    partial void OnOpis_grupyChanging(string value);
    partial void OnOpis_grupyChanged();
    #endregion
		
		public Grupy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grupa", DbType="NVarChar(50)")]
		public string Grupa
		{
			get
			{
				return this._Grupa;
			}
			set
			{
				if ((this._Grupa != value))
				{
					this.OnGrupaChanging(value);
					this.SendPropertyChanging();
					this._Grupa = value;
					this.SendPropertyChanged("Grupa");
					this.OnGrupaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis_grupy", DbType="NVarChar(100)")]
		public string Opis_grupy
		{
			get
			{
				return this._Opis_grupy;
			}
			set
			{
				if ((this._Opis_grupy != value))
				{
					this.OnOpis_grupyChanging(value);
					this.SendPropertyChanging();
					this._Opis_grupy = value;
					this.SendPropertyChanged("Opis_grupy");
					this.OnOpis_grupyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.grupy_uzytkownicy")]
	public partial class grupy_uzytkownicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_grupy;
		
		private int _id_uzytkownika;
		
		private System.Nullable<int> _Data_od;
		
		private System.Nullable<int> _Data_do;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_grupyChanging(int value);
    partial void Onid_grupyChanged();
    partial void Onid_uzytkownikaChanging(int value);
    partial void Onid_uzytkownikaChanged();
    partial void OnData_odChanging(System.Nullable<int> value);
    partial void OnData_odChanged();
    partial void OnData_doChanging(System.Nullable<int> value);
    partial void OnData_doChanged();
    #endregion
		
		public grupy_uzytkownicy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_grupy", DbType="Int NOT NULL")]
		public int id_grupy
		{
			get
			{
				return this._id_grupy;
			}
			set
			{
				if ((this._id_grupy != value))
				{
					this.Onid_grupyChanging(value);
					this.SendPropertyChanging();
					this._id_grupy = value;
					this.SendPropertyChanged("id_grupy");
					this.Onid_grupyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_uzytkownika", DbType="Int NOT NULL")]
		public int id_uzytkownika
		{
			get
			{
				return this._id_uzytkownika;
			}
			set
			{
				if ((this._id_uzytkownika != value))
				{
					this.Onid_uzytkownikaChanging(value);
					this.SendPropertyChanging();
					this._id_uzytkownika = value;
					this.SendPropertyChanged("id_uzytkownika");
					this.Onid_uzytkownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_od", DbType="Int")]
		public System.Nullable<int> Data_od
		{
			get
			{
				return this._Data_od;
			}
			set
			{
				if ((this._Data_od != value))
				{
					this.OnData_odChanging(value);
					this.SendPropertyChanging();
					this._Data_od = value;
					this.SendPropertyChanged("Data_od");
					this.OnData_odChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_do", DbType="Int")]
		public System.Nullable<int> Data_do
		{
			get
			{
				return this._Data_do;
			}
			set
			{
				if ((this._Data_do != value))
				{
					this.OnData_doChanging(value);
					this.SendPropertyChanging();
					this._Data_do = value;
					this.SendPropertyChanged("Data_do");
					this.OnData_doChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uzytkownicy")]
	public partial class uzytkownicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _login;
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private string _tel_kom;
		
		private System.Nullable<bool> _Aktywny;
		
		private System.DateTime _Data_utworzenia;
		
		private System.Nullable<System.DateTime> _Ostatnie_logowanie;
		
		private System.Nullable<System.DateTime> _Konto_aktywne_do;
		
		private System.Nullable<System.DateTime> _Konto_aktywne_od;
		
		private string _Komentarz;
		
		private string _email;
		
		private string _salt;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void Ontel_komChanging(string value);
    partial void Ontel_komChanged();
    partial void OnAktywnyChanging(System.Nullable<bool> value);
    partial void OnAktywnyChanged();
    partial void OnData_utworzeniaChanging(System.DateTime value);
    partial void OnData_utworzeniaChanged();
    partial void OnOstatnie_logowanieChanging(System.Nullable<System.DateTime> value);
    partial void OnOstatnie_logowanieChanged();
    partial void OnKonto_aktywne_doChanging(System.Nullable<System.DateTime> value);
    partial void OnKonto_aktywne_doChanged();
    partial void OnKonto_aktywne_odChanging(System.Nullable<System.DateTime> value);
    partial void OnKonto_aktywne_odChanged();
    partial void OnKomentarzChanging(string value);
    partial void OnKomentarzChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsaltChanging(string value);
    partial void OnsaltChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public uzytkownicy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel_kom", DbType="NVarChar(9)")]
		public string tel_kom
		{
			get
			{
				return this._tel_kom;
			}
			set
			{
				if ((this._tel_kom != value))
				{
					this.Ontel_komChanging(value);
					this.SendPropertyChanging();
					this._tel_kom = value;
					this.SendPropertyChanged("tel_kom");
					this.Ontel_komChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktywny", DbType="Bit")]
		public System.Nullable<bool> Aktywny
		{
			get
			{
				return this._Aktywny;
			}
			set
			{
				if ((this._Aktywny != value))
				{
					this.OnAktywnyChanging(value);
					this.SendPropertyChanging();
					this._Aktywny = value;
					this.SendPropertyChanged("Aktywny");
					this.OnAktywnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_utworzenia", DbType="DateTime NOT NULL")]
		public System.DateTime Data_utworzenia
		{
			get
			{
				return this._Data_utworzenia;
			}
			set
			{
				if ((this._Data_utworzenia != value))
				{
					this.OnData_utworzeniaChanging(value);
					this.SendPropertyChanging();
					this._Data_utworzenia = value;
					this.SendPropertyChanged("Data_utworzenia");
					this.OnData_utworzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ostatnie_logowanie", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ostatnie_logowanie
		{
			get
			{
				return this._Ostatnie_logowanie;
			}
			set
			{
				if ((this._Ostatnie_logowanie != value))
				{
					this.OnOstatnie_logowanieChanging(value);
					this.SendPropertyChanging();
					this._Ostatnie_logowanie = value;
					this.SendPropertyChanged("Ostatnie_logowanie");
					this.OnOstatnie_logowanieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Konto_aktywne_do", DbType="DateTime")]
		public System.Nullable<System.DateTime> Konto_aktywne_do
		{
			get
			{
				return this._Konto_aktywne_do;
			}
			set
			{
				if ((this._Konto_aktywne_do != value))
				{
					this.OnKonto_aktywne_doChanging(value);
					this.SendPropertyChanging();
					this._Konto_aktywne_do = value;
					this.SendPropertyChanged("Konto_aktywne_do");
					this.OnKonto_aktywne_doChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Konto_aktywne_od", DbType="DateTime")]
		public System.Nullable<System.DateTime> Konto_aktywne_od
		{
			get
			{
				return this._Konto_aktywne_od;
			}
			set
			{
				if ((this._Konto_aktywne_od != value))
				{
					this.OnKonto_aktywne_odChanging(value);
					this.SendPropertyChanging();
					this._Konto_aktywne_od = value;
					this.SendPropertyChanged("Konto_aktywne_od");
					this.OnKonto_aktywne_odChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Komentarz", DbType="NVarChar(150)")]
		public string Komentarz
		{
			get
			{
				return this._Komentarz;
			}
			set
			{
				if ((this._Komentarz != value))
				{
					this.OnKomentarzChanging(value);
					this.SendPropertyChanging();
					this._Komentarz = value;
					this.SendPropertyChanged("Komentarz");
					this.OnKomentarzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(80)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salt", DbType="NVarChar(150)")]
		public string salt
		{
			get
			{
				return this._salt;
			}
			set
			{
				if ((this._salt != value))
				{
					this.OnsaltChanging(value);
					this.SendPropertyChanging();
					this._salt = value;
					this.SendPropertyChanged("salt");
					this.OnsaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(150)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
