<?xml version="1.0" encoding="utf-8"?><Database Name="trans" Class="dbtransDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DATABASE2;Initial Catalog=trans;Persist Security Info=True;User ID=valvex" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="transConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Grupy" Member="Grupy">
    <Type Name="Grupy">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Grupa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Opis_grupy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.grupy_uzytkownicy" Member="grupy_uzytkownicy">
    <Type Name="grupy_uzytkownicy">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_grupy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_uzytkownika" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Data_od" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Data_do" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.uzytkownicy" Member="uzytkownicy">
    <Type Name="uzytkownicy">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Imie" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nazwisko" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tel_kom" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="Aktywny" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Data_utworzenia" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Ostatnie_logowanie" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Konto_aktywne_do" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Konto_aktywne_od" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Komentarz" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="salt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
</Database>