#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_SharePoint
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Planowanie szlifiernia_wb")]
	public partial class szlif_operacjeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public szlif_operacjeDataContext() : 
				base(global::WebService_SharePoint.Properties.Settings.Default.Planowanie_szlifiernia_wbConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public szlif_operacjeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public szlif_operacjeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public szlif_operacjeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public szlif_operacjeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Marszruty_szlifiernia_> Marszruty_szlifiernia_s
		{
			get
			{
				return this.GetTable<Marszruty_szlifiernia_>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marszruty_szlifiernia_")]
	public partial class Marszruty_szlifiernia_
	{
		
		private string _Id_wyrobu;
		
		private string _Nazwa_wyrobu;
		
		private string _Kolor;
		
		private string _Nazwa_operacji;
		
		private string _KodOperacjiPS;
		
		private string _Id_operacji;
		
		private System.Nullable<int> _IloscSztZm;
		
		private string _NormaZatwierdzona;
		
		private System.Nullable<int> _Nr_kol_operacji;
		
		public Marszruty_szlifiernia_()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_wyrobu", DbType="NVarChar(255)")]
		public string Id_wyrobu
		{
			get
			{
				return this._Id_wyrobu;
			}
			set
			{
				if ((this._Id_wyrobu != value))
				{
					this._Id_wyrobu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa_wyrobu", DbType="NVarChar(50)")]
		public string Nazwa_wyrobu
		{
			get
			{
				return this._Nazwa_wyrobu;
			}
			set
			{
				if ((this._Nazwa_wyrobu != value))
				{
					this._Nazwa_wyrobu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kolor", DbType="NVarChar(50)")]
		public string Kolor
		{
			get
			{
				return this._Kolor;
			}
			set
			{
				if ((this._Kolor != value))
				{
					this._Kolor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nazwa operacji]", Storage="_Nazwa_operacji", DbType="NVarChar(50)")]
		public string Nazwa_operacji
		{
			get
			{
				return this._Nazwa_operacji;
			}
			set
			{
				if ((this._Nazwa_operacji != value))
				{
					this._Nazwa_operacji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodOperacjiPS", DbType="NChar(5)")]
		public string KodOperacjiPS
		{
			get
			{
				return this._KodOperacjiPS;
			}
			set
			{
				if ((this._KodOperacjiPS != value))
				{
					this._KodOperacjiPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_operacji", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string Id_operacji
		{
			get
			{
				return this._Id_operacji;
			}
			set
			{
				if ((this._Id_operacji != value))
				{
					this._Id_operacji = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IloscSztZm", DbType="Int")]
		public System.Nullable<int> IloscSztZm
		{
			get
			{
				return this._IloscSztZm;
			}
			set
			{
				if ((this._IloscSztZm != value))
				{
					this._IloscSztZm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NormaZatwierdzona", DbType="NChar(3) NOT NULL", CanBeNull=false)]
		public string NormaZatwierdzona
		{
			get
			{
				return this._NormaZatwierdzona;
			}
			set
			{
				if ((this._NormaZatwierdzona != value))
				{
					this._NormaZatwierdzona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nr kol operacji]", Storage="_Nr_kol_operacji", DbType="Int")]
		public System.Nullable<int> Nr_kol_operacji
		{
			get
			{
				return this._Nr_kol_operacji;
			}
			set
			{
				if ((this._Nr_kol_operacji != value))
				{
					this._Nr_kol_operacji = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
