//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_SharePoint.SP2013 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SP2013.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNistTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetNistTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNistTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetNistTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INW_do_korekty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable INW_do_korekty(string nr_komisji);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INW_do_korekty", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> INW_do_korektyAsync(string nr_komisji);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INW_Zapisy_komisji", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable INW_Zapisy_komisji(string nr_komisji);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INW_Zapisy_komisji", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> INW_Zapisy_komisjiAsync(string nr_komisji);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Location", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Get_Location(string comm_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Location", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> Get_LocationAsync(string comm_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDB_stan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateDB_stan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDB_stan", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateDB_stanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INW_KOMUNIKATY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] INW_KOMUNIKATY(string nr_kom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INW_KOMUNIKATY", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> INW_KOMUNIKATYAsync(string nr_kom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_spis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Guid Insert_spis(bool anulowany, System.DateTime data_zapisu, double ilosc, string jm, string komentarz, double koszt, string loc, string mag, int litm, string indeks, string nr_komisji, System.Guid Gd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_spis", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> Insert_spisAsync(bool anulowany, System.DateTime data_zapisu, double ilosc, string jm, string komentarz, double koszt, string loc, string mag, int litm, string indeks, string nr_komisji, System.Guid Gd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDB_indeksy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateDB_indeksy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDB_indeksy", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateDB_indeksyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPO_Delete_item", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IPO_Delete_item(int item_id_itm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPO_Delete_item", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IPO_Delete_itemAsync(int item_id_itm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPO_Delete_Warehouse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IPO_Delete_Warehouse(string whid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPO_Delete_Warehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IPO_Delete_WarehouseAsync(string whid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPO_Update_avail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IPO_Update_avail(int item_id_itm, decimal qty, string warehouse_id, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPO_Update_avail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IPO_Update_availAsync(int item_id_itm, decimal qty, string warehouse_id, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOupdateItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void IPOupdateItem(int item_id_itm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOupdateItem", ReplyAction="*")]
        System.Threading.Tasks.Task IPOupdateItemAsync(int item_id_itm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendAlert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SendAlert(string to, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendAlert", ReplyAction="*")]
        System.Threading.Tasks.Task SendAlertAsync(string to, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPO_popraw_indeksy_w_IPO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void IPO_popraw_indeksy_w_IPO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPO_popraw_indeksy_w_IPO", ReplyAction="*")]
        System.Threading.Tasks.Task IPO_popraw_indeksy_w_IPOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/local_New_Item_SP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void local_New_Item_SP(string title, string kod, string user, string typ, string opis, string operacja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/local_New_Item_SP", ReplyAction="*")]
        System.Threading.Tasks.Task local_New_Item_SPAsync(string title, string kod, string user, string typ, string opis, string operacja);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WebService_SharePoint.SP2013.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WebService_SharePoint.SP2013.Service1Soap>, WebService_SharePoint.SP2013.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetNistTime() {
            return base.Channel.GetNistTime();
        }
        
        public System.Threading.Tasks.Task<string> GetNistTimeAsync() {
            return base.Channel.GetNistTimeAsync();
        }
        
        public System.Data.DataTable INW_do_korekty(string nr_komisji) {
            return base.Channel.INW_do_korekty(nr_komisji);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> INW_do_korektyAsync(string nr_komisji) {
            return base.Channel.INW_do_korektyAsync(nr_komisji);
        }
        
        public System.Data.DataTable INW_Zapisy_komisji(string nr_komisji) {
            return base.Channel.INW_Zapisy_komisji(nr_komisji);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> INW_Zapisy_komisjiAsync(string nr_komisji) {
            return base.Channel.INW_Zapisy_komisjiAsync(nr_komisji);
        }
        
        public string[] Get_Location(string comm_id) {
            return base.Channel.Get_Location(comm_id);
        }
        
        public System.Threading.Tasks.Task<string[]> Get_LocationAsync(string comm_id) {
            return base.Channel.Get_LocationAsync(comm_id);
        }
        
        public string UpdateDB_stan() {
            return base.Channel.UpdateDB_stan();
        }
        
        public System.Threading.Tasks.Task<string> UpdateDB_stanAsync() {
            return base.Channel.UpdateDB_stanAsync();
        }
        
        public string[] INW_KOMUNIKATY(string nr_kom) {
            return base.Channel.INW_KOMUNIKATY(nr_kom);
        }
        
        public System.Threading.Tasks.Task<string[]> INW_KOMUNIKATYAsync(string nr_kom) {
            return base.Channel.INW_KOMUNIKATYAsync(nr_kom);
        }
        
        public System.Guid Insert_spis(bool anulowany, System.DateTime data_zapisu, double ilosc, string jm, string komentarz, double koszt, string loc, string mag, int litm, string indeks, string nr_komisji, System.Guid Gd) {
            return base.Channel.Insert_spis(anulowany, data_zapisu, ilosc, jm, komentarz, koszt, loc, mag, litm, indeks, nr_komisji, Gd);
        }
        
        public System.Threading.Tasks.Task<System.Guid> Insert_spisAsync(bool anulowany, System.DateTime data_zapisu, double ilosc, string jm, string komentarz, double koszt, string loc, string mag, int litm, string indeks, string nr_komisji, System.Guid Gd) {
            return base.Channel.Insert_spisAsync(anulowany, data_zapisu, ilosc, jm, komentarz, koszt, loc, mag, litm, indeks, nr_komisji, Gd);
        }
        
        public string UpdateDB_indeksy() {
            return base.Channel.UpdateDB_indeksy();
        }
        
        public System.Threading.Tasks.Task<string> UpdateDB_indeksyAsync() {
            return base.Channel.UpdateDB_indeksyAsync();
        }
        
        public string IPO_Delete_item(int item_id_itm) {
            return base.Channel.IPO_Delete_item(item_id_itm);
        }
        
        public System.Threading.Tasks.Task<string> IPO_Delete_itemAsync(int item_id_itm) {
            return base.Channel.IPO_Delete_itemAsync(item_id_itm);
        }
        
        public string IPO_Delete_Warehouse(string whid) {
            return base.Channel.IPO_Delete_Warehouse(whid);
        }
        
        public System.Threading.Tasks.Task<string> IPO_Delete_WarehouseAsync(string whid) {
            return base.Channel.IPO_Delete_WarehouseAsync(whid);
        }
        
        public string IPO_Update_avail(int item_id_itm, decimal qty, string warehouse_id, string location) {
            return base.Channel.IPO_Update_avail(item_id_itm, qty, warehouse_id, location);
        }
        
        public System.Threading.Tasks.Task<string> IPO_Update_availAsync(int item_id_itm, decimal qty, string warehouse_id, string location) {
            return base.Channel.IPO_Update_availAsync(item_id_itm, qty, warehouse_id, location);
        }
        
        public void IPOupdateItem(int item_id_itm) {
            base.Channel.IPOupdateItem(item_id_itm);
        }
        
        public System.Threading.Tasks.Task IPOupdateItemAsync(int item_id_itm) {
            return base.Channel.IPOupdateItemAsync(item_id_itm);
        }
        
        public void SendAlert(string to, string subject, string body) {
            base.Channel.SendAlert(to, subject, body);
        }
        
        public System.Threading.Tasks.Task SendAlertAsync(string to, string subject, string body) {
            return base.Channel.SendAlertAsync(to, subject, body);
        }
        
        public void IPO_popraw_indeksy_w_IPO() {
            base.Channel.IPO_popraw_indeksy_w_IPO();
        }
        
        public System.Threading.Tasks.Task IPO_popraw_indeksy_w_IPOAsync() {
            return base.Channel.IPO_popraw_indeksy_w_IPOAsync();
        }
        
        public System.Data.DataTable GetItems() {
            return base.Channel.GetItems();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetItemsAsync() {
            return base.Channel.GetItemsAsync();
        }
        
        public void local_New_Item_SP(string title, string kod, string user, string typ, string opis, string operacja) {
            base.Channel.local_New_Item_SP(title, kod, user, typ, opis, operacja);
        }
        
        public System.Threading.Tasks.Task local_New_Item_SPAsync(string title, string kod, string user, string typ, string opis, string operacja) {
            return base.Channel.local_New_Item_SPAsync(title, kod, user, typ, opis, operacja);
        }
    }
}
