//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_SharePoint.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATABASE2;Initial Catalog=trans;Persist Security Info=True;User ID=va" +
            "lvex")]
        public string transConnectionString {
            get {
                return ((string)(this["transConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DB2008;Initial Catalog=PS_PROD;Persist Security Info=True;User ID=val" +
            "vex")]
        public string PS_PRODConnectionString1 {
            get {
                return ((string)(this["PS_PRODConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=database2;Initial Catalog=KARTY_PRODUKCJI;Persist Security Info=True;" +
            "User ID=valvex")]
        public string KARTY_PRODUKCJIConnectionString {
            get {
                return ((string)(this["KARTY_PRODUKCJIConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=database2;Initial Catalog=trans;Persist Security Info=True;User ID=va" +
            "lvex;Password=valvex123")]
        public string transConnectionString1 {
            get {
                return ((string)(this["transConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATABASE2;Initial Catalog=\"Planowanie szlifiernia_wb\";Persist Securit" +
            "y Info=True;User ID=valvex")]
        public string Planowanie_szlifiernia_wbConnectionString {
            get {
                return ((string)(this["Planowanie_szlifiernia_wbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=database2;Initial Catalog=\"Planowanie szlifiernia_wb\";User ID=valvex;" +
            "Password=valvex123;Encrypt=False;TrustServerCertificate=True")]
        public string Planowanie_szlifiernia_wbConnectionString1 {
            get {
                return ((string)(this["Planowanie_szlifiernia_wbConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATABASE2;Initial Catalog=RAPORTY;Persist Security Info=True;User ID=" +
            "valvex")]
        public string RAPORTYConnectionString {
            get {
                return ((string)(this["RAPORTYConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=database2;Initial Catalog=RAPORTY;Persist Security Info=True;User ID=" +
            "valvex;Password=valvex123")]
        public string RAPORTYConnectionString1 {
            get {
                return ((string)(this["RAPORTYConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=db2008;Initial Catalog=PS_PROD;Persist Security Info=True;User ID=val" +
            "vex;Password=valvex123")]
        public string PS_PRODConnectionString {
            get {
                return ((string)(this["PS_PRODConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATABASE2;Initial Catalog=KARTY_PRODUKCJI;User ID=valvex;Password=val" +
            "vex123;Encrypt=False;TrustServerCertificate=True")]
        public string KARTY_PRODUKCJIConnectionString1 {
            get {
                return ((string)(this["KARTY_PRODUKCJIConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATABASE2;Initial Catalog=Baza_technol;Persist Security Info=True;Use" +
            "r ID=valvex")]
        public string Baza_technolConnectionString {
            get {
                return ((string)(this["Baza_technolConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATABASE2;Initial Catalog=Baza_technol;Persist Security Info=True;Use" +
            "r ID=valvex;Password=valvex123")]
        public string Baza_technolConnectionString1 {
            get {
                return ((string)(this["Baza_technolConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=database2;Initial Catalog=KARTY_PRODUKCJI;Persist Security Info=True;" +
            "User ID=valvex;Password=valvex123")]
        public string KARTY_PRODUKCJIConnectionString2 {
            get {
                return ((string)(this["KARTY_PRODUKCJIConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATABASE2;Initial Catalog=RAPORTY;Persist Security Info=True;User ID=" +
            "valvex;Password=valvex123")]
        public string RAPORTYConnectionString2 {
            get {
                return ((string)(this["RAPORTYConnectionString2"]));
            }
        }
    }
}
